// All route imports and app.route() mounting in one place.
// index.ts stays thin: create app, apply middleware, call mountRoutes(app), export.
import { Hono } from 'hono';
import type { HonoEnv } from '../utils/types';

import authRoutes from './auth';
import ssoRoutes from './sso';
import cockpitRoutes from './cockpit';
import launchRoutes from './launch';
import participantsRoutes from './participants';
import contractsRoutes from './contracts';
import invoicesRoutes from './invoices';
import projectsRoutes from './projects';
import docGenerationRoutes from './doc-generation';
import projectScheduleRoutes from './project-schedule';
import riskRoutes from './risk';
import clearingDisclosureRoutes from './clearing-disclosure';
import settlementDvpRoutes from './settlement-dvp';
import marginGateRoutes from './margin-gate';
import tradingRoutes from './trading';
import settlementRoutes from './settlement';
import carbonRoutes from './carbon';
import esgRoutes from './esg';
import esgReportsRoutes from './esg-reports';
import watershedRoutes, { cpPortal as counterpartyPortalRoutes } from './watershed';
import platformRoutes from './platform';
import roleCompletionsRoutes from './role-completions';
import gridRoutes from './grid';
import procurementRoutes from './procurement';
import dealroomRoutes from './dealroom';
import modulesRoutes from './modules';
import popiaRoutes from './popia';
import intelligenceRoutes from './intelligence';
import briefingRoutes from './briefing';
import meteringRoutes from './metering';
import onaRoutes from './ona';
import pipelineRoutes from './pipeline';
import vaultRoutes from './vault';
import threadsRoutes from './threads';
import marketplaceRoutes from './marketplace';
import adminRoutes from './admin';
import supportRoutes from './support';
import aiRoutes from './ai';
import loiRoutes from './lois';
import offtakerRoutes from './offtaker';
import funderRoutes from './funder';
import regulatorRoutes from './regulator';
import regulatorSuiteRoutes from './regulator-suite';
import gridOperatorRoutes from './grid-operator';
import traderRiskRoutes from './trader-risk';
import lenderSuiteRoutes from './lender-suite';
import ippLifecycleRoutes from './ipp-lifecycle';
import offtakerSuiteRoutes from './offtaker-suite';
import carbonRegistryRoutes from './carbon-registry';
import carbonArticle6Routes from './carbon-article-6';
import regulatorInboxRoutes from './regulator-inbox';
import roleActionsRoutes from './role-actions';
import feedRoutes from './feed';
import insightsRoutes from './insights';
import lenderDunningRoutes from './lender-dunning';
import offtakerObligationsRoutes from './offtaker-obligations';
import gridWheelingChargesRoutes from './grid-wheeling-charges';
import traderMmComplianceRoutes from './trader-mm-compliance';
import ippBondsRoutes from './ipp-bonds';
import carbonMrvChainRoutes from './carbon-mrv-chain';
import esumsCommissioningRoutes from './esums-commissioning';
import gridDispatchNominationsRoutes from './grid-dispatch-nominations';
import supportTicketChainRoutes from './support-ticket-chain';
import warrantyClaimChainRoutes from './warranty-claim-chain';
import woChainRoutes from './wo-chain';
import carbonRetirementChainRoutes from './carbon-retirement-chain';
import plannedOutageChainRoutes from './planned-outage-chain';
import procurementChainRoutes from './procurement-chain';
import codChainRoutes from './cod-chain';
import drawdownChainRoutes from './drawdown-chain';
import ppaContractChainRoutes from './ppa-contract-chain';
import insuranceClaimChainRoutes from './insurance-claim-chain';
import prChainRoutes from './pr-chain';
import hseIncidentChainRoutes from './hse-incident-chain';
import cyberIncidentChainRoutes from './cyber-incident-chain';
import edCommitmentChainRoutes from './ed-commitment-chain';
import gcaChainRoutes from './gca-chain';
import poslimitChainRoutes from './poslimit-chain';
import disbursementChainRoutes from './disbursement-chain';
import dispositionChainRoutes from './disposition-chain';
import takeOrPayChainRoutes from './take-or-pay-chain';
import licenceRenewalChainRoutes from './licence-renewal-chain';
import loadCurtailmentChainRoutes from './load-curtailment-chain';
import vendorEscalationChainRoutes from './vendor-escalation-chain';
import bestExecutionChainRoutes from './best-execution-chain';
import carbonRegistrationChainRoutes from './carbon-registration-chain';
import covenantCertificateChainRoutes from './covenant-certificate-chain';
import tariffIndexationChainRoutes from './tariff-indexation-chain';
import complianceInspectionChainRoutes from './compliance-inspection-chain';
import problemManagementChainRoutes from './problem-management-chain';
import carbonReversalChainRoutes from './carbon-reversal-chain';
import tariffDeterminationChainRoutes from './tariff-determination-chain';
import tradeReportingChainRoutes from './trade-reporting-chain';
import loanDefaultChainRoutes from './loan-default-chain';
import curtailmentClaimChainRoutes from './curtailment-claim-chain';
import changeEnablementChainRoutes from './change-enablement-chain';
import carbonOffsetClaimChainRoutes from './carbon-offset-claim-chain';
import licenceApplicationChainRoutes from './licence-application-chain';
import reserveActivationChainRoutes from './reserve-activation-chain';
import availabilityGuaranteeChainRoutes from './availability-guarantee-chain';
import marketAbuseChainRoutes from './market-abuse-chain';
import creditOriginationChainRoutes from './credit-origination-chain';
import paymentSecurityChainRoutes from './payment-security-chain';
import securityRemediationChainRoutes from './security-remediation-chain';
import creditingRenewalChainRoutes from './crediting-renewal-chain';
import ssegRegistrationChainRoutes from './sseg-registration-chain';
import gridCapacityAllocationChainRoutes from './grid-capacity-allocation-chain';
import pmComplianceChainRoutes from './pm-compliance-chain';
import algoCertChainRoutes from './algo-cert-chain';
import loanTransferChainRoutes from './loan-transfer-chain';
import ppaTerminationChainRoutes from './ppa-termination-chain';
import warrantyRecoveryChainRoutes from './warranty-recovery-chain';
import permitToWorkChainRoutes from './permit-to-work-chain';
import carbonErpaChainRoutes from './carbon-erpa-chain';
import complaintResolutionChainRoutes from './complaint-resolution-chain';
import gridCodeComplianceChainRoutes from './grid-code-compliance-chain';
import counterpartyMarginChainRoutes from './counterparty-margin-chain';
import securityPerfectionChainRoutes from './security-perfection-chain';
import recLifecycleChainRoutes from './rec-lifecycle-chain';
import assetPrognosticsChainRoutes from './asset-prognostics-chain';
import sparePartsProvisioningChainRoutes from './spare-parts-provisioning-chain';
import poaCpaInclusionChainRoutes from './poa-cpa-inclusion-chain';
import levyAssessmentChainRoutes from './levy-assessment-chain';
import connectionEnergizationChainRoutes from './connection-energization-chain';
import tradeAllocationChainRoutes from './trade-allocation-chain';
import reserveAccountChainRoutes from './reserve-account-chain';
import ppaChangeInLawChainRoutes from './ppa-change-in-law-chain';
import generationRevenueAssuranceChainRoutes from './generation-revenue-assurance-chain';
import serviceContractChainRoutes from './service-contract-chain';
import projectChangeOrderChainRoutes from './project-change-order-chain';
import carbonIssuanceChainRoutes from './carbon-issuance-chain';
import consultationNoticeChainRoutes from './consultation-notice-chain';
import blackStartChainRoutes from './black-start-chain';
import settlementFailChainRoutes from './settlement-fail-chain';
import dscrMonitoringChainRoutes from './dscr-monitoring-chain';
import ppaNominationChainRoutes from './ppa-nomination-chain';
import bessSohChainRoutes from './bess-soh-chain';
import oemFcoChainRoutes from './oem-fco-chain';
import benchmarkTransitionChainRoutes from './benchmark-transition-chain';
import ccpAssessmentChainRoutes from './ccp-assessment-chain';
import projectRiskChainRoutes from './project-risk-chain';
import enforcementActionChainRoutes from './enforcement-action-chain';
import rezCapacityChainRoutes from './rez-capacity-chain';
import sllKpiChainRoutes from './sll-kpi-chain';
import submittalRfiChainRoutes from './submittal-rfi-chain';
import dfrChainRoutes from './dfr-chain';
import punchListChainRoutes from './punch-list-chain';
import itpChainRoutes from './itp-chain';
import handoverDossierChainRoutes from './handover-dossier-chain';
import ppaAnnualReconChainRoutes from './ppa-annual-recon-chain';
import soilingAuditChainRoutes from './soiling-audit-chain';
import esgDisclosureChainRoutes from './esg-disclosure-chain';
import serviceRequestChainRoutes from './service-request-chain';
import imbalanceSettlementChainRoutes from './imbalance-settlement-chain';
import enforcementActionS35ChainRoutes from './enforcement-action-s35-chain';
import pretradeCreditChainRoutes from './pretrade-credit-chain';
import loanRestructureChainRoutes from './loan-restructure-chain';
import carbonCreditRatingChainRoutes from './carbon-credit-rating-chain';
import transmissionOutageChainRoutes from './transmission-outage-chain';
import pnlAttributionChainRoutes from './pnl-attribution-chain';
import ippScheduleChainRoutes from './ipp-schedule-chain';
import ippEvmChainRoutes from './ipp-evm-chain';
import ippDocumentControlChainRoutes from './ipp-document-control-chain';
import ippSubmittalRoute from './ipp-submittal';
import ippRfiRoute from './ipp-rfi';
import ippChangeOrderRoute from './ipp-change-order';
import auditChainRoute from './audit-chain';
import regulatorExportRoutes from './regulator-export';
import reconciliationAttestationRoutes from './reconciliation-attestation';
import controlEnvironmentAuditRoutes from './control-environment-audit';
import scadaConnectorRoutes from './scada-connector';
import mqttOpcuaConnectorRoutes from './mqtt-opcua-connector';
import strateSwiftConnectorRoutes from './strate-swift-connector';
import sapOracleErpConnectorRoutes from './sap-oracle-erp-connector';
import governmentFilingConnectorRoutes from './government-filing-connector';
import anomalyDetectionMlRoutes from './anomaly-detection-ml';
import rulPredictionMlRoutes from './rul-prediction-ml';
import faultFingerprintMlRoutes from './fault-fingerprint-ml';
import nttComparisonBatteryRoutes from './ntt-comparison-battery';
import stageGateRoutes from './stage-gate';
import ippIssuesRoutes from './ipp-issues';
import ippRiskRoutes from './ipp-risk';
import ippStakeholderRoutes from './ipp-stakeholder';
import ippLessonsLearnedRoutes from './ipp-lessons-learned';
import ippNcrRoutes from './ipp-ncr';
import ippMethodStatementRoutes from './ipp-method-statement';
import ippEnvMonitoringRoutes from './ipp-env-monitoring';
import ippMirRoutes from './ipp-mir';
import ippSubcontractorRoutes from './ipp-subcontractor';
import ippProgressClaimRoutes from './ipp-progress-claim';
import ippTqRoutes from './ipp-tq';
import ippDiaryRoutes from './ipp-diary';
import ippSiteInstructionRoutes from './ipp-site-instruction';
import ippDlpDefectRoutes from './ipp-dlp-defect';
import ippVariationOrderRoutes from './ipp-variation-order';
import ippPaymentCertRoutes from './ipp-payment-cert';
import ippFinalCompletionRoutes from './ipp-final-completion';
import ippOmHandoverRoutes from './ipp-om-handover';
import ippLandRegisterRoutes from './ipp-land-register';
import ippEnvClosureRoutes from './ipp-env-closure';
import ippCommissioningTestRoutes from './ipp-commissioning-test';
import ippIeCertRoutes from './ipp-ie-cert';
import ippTpaRoutes from './ipp-tpa';
import ippPpaVariationRoutes from './ipp-ppa-variation';
import ippChangeOfControlRoutes from './ipp-change-of-control';
import ippRefinancingRoutes from './ipp-refinancing';
import ippFmRoutes from './ipp-fm';
import ippAnnualReportRoutes from './ipp-annual-report';
import ippContractorDefaultRoutes from './ipp-contractor-default';
import ippEcoReportRoutes from './ipp-eco-report';
import ippLtaCertificateRoutes from './ipp-lta-certificate';
import ippLandAmendmentRoutes from './ipp-land-amendment';
import ippCommunityTrustRoutes from './ipp-community-trust';
import ippGridComplianceRoutes from './ipp-grid-compliance';
import ippCccRoutes from './ipp-ccc';
import ippOmContractRoutes from './ipp-om-contract';
import ippBfsRoutes from './ipp-bfs';
import ippEaAmendmentRoutes from './ipp-ea-amendment';
import ippWulRoutes from './ipp-wul';
import ippHraRoutes from './ipp-hra';
import ippAelRoutes from './ipp-ael';
import ippForceMajeureRoutes from './ipp-force-majeure';
import ippLcReportRoutes from './ipp-lc-report';
import ippMilestoneCertRoutes from './ipp-milestone-cert';
import ippEsmrRoutes from './ipp-esmr';
import ippIeAnnualReviewRoutes from './ipp-iear';
import ippInsuranceRenewalRoutes from './ipp-insr';
import ippPerfSecurityRoutes from './ipp-perf-security';
import ippCepComplianceRoutes from './ipp-cep-compliance';
import ippSedComplianceRoutes from './ipp-sed-compliance';
import ippBbbeeVerificationRoutes from './ipp-bbbee-verification';
import ippLenderReportingRoutes from './ipp-lender-reporting';
import ippLicenceReturnsRoutes from './ipp-licence-returns';
import ippReippppReportsRoutes from './ipp-reipppp-reports';
import ippEquityTransferRoutes from './ipp-equity-transfer';
import ippQuarterlyGenReportRoutes from './ipp-quarterly-gen-reports';
import ippAnnualComplianceAssessmentRoutes from './ipp-annual-compliance-assessments';
import ippAnnualAuditRoutes from './ipp-annual-audits';
import ippEmpComplianceReportRoutes from './ipp-emp-compliance-reports';
import ippCpTrackerRoutes from './ipp-cp-tracker';
import ippLicenceObligationRoutes from './ipp-licence-obligations';
import { facilityAmendmentRoutes } from './facility-amendment-chain';
import { esapComplianceRoutes } from './esap-compliance-chain';
import { protectionRelayRoutes } from './protection-relay-chain';
import { unservedEnergyRoutes } from './unserved-energy-chain';
import stationParticipantLinkRoutes from './station-participant-links';
import adminPlatformRoutes from './admin-platform';
import settlementAutoRoutes from './settlement-automation';
import imbalanceRoutes from './imbalance';
import dataTierRoutes from './data-tier';
import aiBriefsRoutes from './ai-briefs';
import realtimeRoutes from './realtime';
import siemRoutes from './siem';
import reportsRoutes from './reports';
import telemetryRoutes from './telemetry';
import monitoringRoutes from './monitoring';
import lookupRoutes from './lookup';
import adminRevenueRoutes from './admin-revenue';
import adminMarketHaltRoutes from './admin-market-halt';
import backupRoutes from './backup';
import searchRoutes from './search';
import notificationsRoutes from './notifications';
import scheduleRoutes from './schedule';
import esumsOmRoutes from './esums-om';
import esumsOmIntelRoutes from './esums-om-intel';
import esumsOmAnalysisRoutes from './esums-om-analysis';
import { portalAdmin as esumsOmPortalAdmin, portalPublic as esumsOmPortalPublic } from './esums-om-portal';
import esumsIngestRoutes from './esums-ingest';
import esumsDataSourcesRoutes from './esums-data-sources';
import esumsProjectsRoutes from './esums-projects';
import esumsOmSolaxRoutes from './esums-solax';
import esumsManufacturersRoutes from './esums-manufacturers';
import esumsAccrualsRoutes, { esumsInvoiceRoutes, esumsCreditRoutes } from './esums-accruals';
import platformFeaturesRoutes from './platform-features';
import onboardingRoutes from './onboarding';
import onboardingChecklistRoutes from './onboarding-checklist';
import onboardingKycRoutes from './onboarding-kyc';
import {
  mfa as mfaRoutes,
  kyc as kycRoutes,
  consent as consentRoutes,
  popia as popiaSelfServiceRoutes,
  regulator as regulatorReportRoutes,
  status as publicStatusRoutes,
} from './go-live';
import authDeepRoutes from './auth-deep';
import kycDeepRoutes from './kyc-deep';
import { admin as statusDeepAdmin, pub as statusDeepPub } from './status-deep';
import popiaDeepRoutes from './popia-deep';
import reportsDeepRoutes from './reports-deep';
import tradingDeepRoutes from './trading-deep';
import settlementDeepRoutes from './settlement-deep';
import { ipp as ippDeepRoutes, lender as lenderDeepRoutes, carbon as carbonDeepRoutes } from './depth-3';
import gridL5Routes from './grid-l5';
import { admin as regulatorL5Admin, pub as regulatorL5Pub } from './regulator-l5';
import tradingClearingL5Routes from './trading-clearing-l5';
import { admin as auditL5Admin, pub as auditL5Pub } from './audit-l5';
import marketplaceL5Routes from './marketplace-l5';
import aiAssistantRoutes from './ai-assistant';
import polishRoutes from './polish';
import publicLegalRoutes from './public-legal';
import businessDepthRoutes from './business-depth';
import bulkOpsRoutes from './bulk-ops';
import uxStateRoutes from './ux-state';
import documentsRoutes from './documents';
import pdfRoutes from './pdf';
import rbacRoutes from './rbac';
import printPacksRoutes from './print-packs';
import kycChainRoutes from './kyc-chain';
import smartMeterChainRoutes from './smart-meter-chain';
import carbonTaxChainRoutes from './carbon-tax-chain';
import fsccChainRoutes from './fsca-compliance-chain';
import greenBondChainRoutes from './green-bond-chain';
import capAdequacyChainRoutes from './capital-adequacy-chain';
import slbKpiChainRoutes from './slb-kpi-chain';
import demandResponseChainRoutes from './demand-response-chain';
import carbonRegistryTransferChainRoutes from './carbon-registry-transfer-chain';
import milestoneVarianceChainRoutes from './milestone-variance-chain';
import csatChainRoutes from './csat-chain';
import publicConsultationChainRoutes from './public-consultation-chain';
import greenTariffChainRoutes from './green-tariff-chain';
import substationAssetChainRoutes from './substation-asset-chain';
import dscrReportChainRoutes from './dscr-report-chain';
import methodologyAmendmentChainRoutes from './methodology-amendment-chain';
import esapMonitoringChainRoutes from './esap-monitoring-chain';
import eopActivationChainRoutes from './eop-activation-chain';
import fscaConductReportChainRoutes from './fsca-conduct-report-chain';
import slaPerformanceReportChainRoutes from './sla-performance-report-chain';
import creditInsuranceChainRoutes from './credit-insurance-chain';
import wheelingAccessChainRoutes from './wheeling-access-chain';
import marketConductExamChainRoutes from './market-conduct-exam-chain';
import exportCurtailmentChainRoutes from './export-curtailment-chain';
import crossBorderTradeChainRoutes from './cross-border-trade-chain';
import cpClearanceChainRoutes from './cp-clearance-chain';
import gtiaChainRoutes from './gtia-chain';
import scope3DisclosureChainRoutes from './scope3-disclosure-chain';
import vcmProjectDevelopmentChainRoutes from './vcm-project-development-chain';
import carbonBudgetChainRoutes from './carbon-budget-chain';
import recDeviceRegistrationChainRoutes from './rec-device-registration-chain';
import recIssuanceChainRoutes from './rec-issuance-chain';
import vcmOrderBookRoutes from './vcm-order-book';
import sustainabilityMarketplaceRoutes from './sustainability-marketplace';
import sustainabilityTransactionChainRoutes from './sustainability-transaction-chain';
import certBundleChainRoutes from './certificate-bundle-chain';
import subscriptionBillingChainRoutes from './subscription-billing-chain';
import virtualPpaSettlementChainRoutes from './virtual-ppa-settlement-chain';
import cbtSedChainRoutes from './cbt-sed-chain';
import constructionCostReportChainRoutes from './construction-cost-report-chain';
import isdaAgreementChainRoutes from './isda-agreement-chain';
import dataSubjectRequestChainRoutes from './data-subject-request-chain';
import interconnectorScheduleChainRoutes from './interconnector-schedule-chain';
import nationalDashboardRoutes from './national-dashboard';
import horizonRoutes from './horizon';
import threadRoutes from './thread';
import ledgerRoutes from './ledger';
import dealsRoutes from './deals';

// Hono's authMiddleware is applied per-module inside each route file using
// r.use('*', authMiddleware). This function only mounts the paths.
export function mountRoutes(app: Hono<HonoEnv>): void {
  // Auth routes
  app.route('/api/auth', authRoutes);
  app.route('/api/auth/sso', ssoRoutes);
  app.route('/api/cockpit', cockpitRoutes);
  app.route('/api/launch', launchRoutes);

  // Protected routes
  app.route('/api/participants', participantsRoutes);
  app.route('/api/contracts', contractsRoutes);
  app.route('/api/invoices', invoicesRoutes);
  app.route('/api/projects', projectsRoutes);
  app.route('/api/doc-gen', docGenerationRoutes);
  app.route('/api/projects/:projectId/schedule', projectScheduleRoutes);
  app.route('/api/risk', riskRoutes);
  app.route('/api/clearing/disclosure', clearingDisclosureRoutes);
  app.route('/api/settlement/dvp', settlementDvpRoutes);
  app.route('/api/clearing/margin-gate', marginGateRoutes);
  app.route('/api/trading', tradingRoutes);
  app.route('/api/role-actions', roleActionsRoutes);
  app.route('/api/feed', feedRoutes);
  app.route('/api/insights', insightsRoutes);
  app.route('/api/settlement', settlementRoutes);
  app.route('/api/carbon', carbonRoutes);
  app.route('/api/esg', esgRoutes);
  app.route('/api/esg-reports', esgReportsRoutes);
  app.route('/api/watershed', watershedRoutes);
  app.route('/api/portal', counterpartyPortalRoutes);
  app.route('/api/platform', platformRoutes);
  app.route('/api/roles', roleCompletionsRoutes);
  app.route('/api/grid', gridRoutes);
  app.route('/api/procurement', procurementRoutes);
  app.route('/api/dealroom', dealroomRoutes);
  app.route('/api/modules', modulesRoutes);
  app.route('/api/popia', popiaRoutes);
  app.route('/api/intelligence', intelligenceRoutes);
  app.route('/api/briefing', briefingRoutes);
  app.route('/api/metering', meteringRoutes);
  app.route('/api/ona', onaRoutes);
  app.route('/api/pipeline', pipelineRoutes);
  app.route('/api/vault', vaultRoutes);
  app.route('/api/threads', threadsRoutes);
  app.route('/api/marketplace', marketplaceRoutes);
  app.route('/api/admin', adminRoutes);
  app.route('/api/support', supportRoutes);
  app.route('/api/ai', aiRoutes);
  app.route('/api/lois', loiRoutes);
  app.route('/api/offtaker', offtakerRoutes);
  app.route('/api/funder', funderRoutes);
  // /api/regulator is intentionally mounted three times (lines below + line ~650):
  //   regulatorRoutes      → /filings, /market-summary
  //   regulatorSuiteRoutes → /licences, /tariff-submissions
  //   regulatorReportRoutes (reports.ts) → /catalog, /ledger, /registry, /:role
  // Hono matches in registration order; the /:role wildcard in reports only fires
  // for paths not claimed by the first two routers. No conflicts verified.
  app.route('/api/regulator', regulatorRoutes);
  app.route('/api/regulator', regulatorSuiteRoutes);
  app.route('/api/grid-operator', gridOperatorRoutes);
  app.route('/api/trader-risk', traderRiskRoutes);
  app.route('/api/lender', lenderSuiteRoutes);
  app.route('/api/ipp', ippLifecycleRoutes);
  app.route('/api/offtaker-suite', offtakerSuiteRoutes);
  app.route('/api/carbon-registry', carbonRegistryRoutes);
  app.route('/api/carbon/article-6', carbonArticle6Routes);
  app.route('/api/regulator/inbox', regulatorInboxRoutes);
  app.route('/api/lender/dunning', lenderDunningRoutes);
  app.route('/api/offtaker/obligations', offtakerObligationsRoutes);
  app.route('/api/grid/wheeling-charges', gridWheelingChargesRoutes);
  app.route('/api/trader/mm-compliance', traderMmComplianceRoutes);
  app.route('/api/ipp/bonds', ippBondsRoutes);
  app.route('/api/carbon/mrv-chain', carbonMrvChainRoutes);
  app.route('/api/esums/commissioning', esumsCommissioningRoutes);
  app.route('/api/grid/dispatch-nominations', gridDispatchNominationsRoutes);
  app.route('/api/support/ticket-chain', supportTicketChainRoutes);
  app.route('/api/esums/warranty-claims', warrantyClaimChainRoutes);
  app.route('/api/esums/wo-chain', woChainRoutes);
  app.route('/api/carbon/retirement-chain', carbonRetirementChainRoutes);
  app.route('/api/grid/planned-outages', plannedOutageChainRoutes);
  app.route('/api/ipp/procurement-chain', procurementChainRoutes);
  app.route('/api/ipp/cod-chain', codChainRoutes);
  app.route('/api/lender/drawdown-chain', drawdownChainRoutes);
  app.route('/api/offtaker/ppa-contract-chain', ppaContractChainRoutes);
  app.route('/api/insurance/claim-chain', insuranceClaimChainRoutes);
  app.route('/api/esums/pr-chain', prChainRoutes);
  app.route('/api/hse/incident-chain', hseIncidentChainRoutes);
  app.route('/api/cyber/incident-chain', cyberIncidentChainRoutes);
  app.route('/api/ed/commitment-chain', edCommitmentChainRoutes);
  app.route('/api/gca/connection-chain', gcaChainRoutes);
  app.route('/api/poslimit/chain', poslimitChainRoutes);
  app.route('/api/disbursement/chain', disbursementChainRoutes);
  app.route('/api/disposition/chain', dispositionChainRoutes);
  app.route('/api/take-or-pay/chain', takeOrPayChainRoutes);
  app.route('/api/licence/renewal/chain', licenceRenewalChainRoutes);
  app.route('/api/load-curtailment/chain', loadCurtailmentChainRoutes);
  app.route('/api/esums/vendor-escalation/chain', vendorEscalationChainRoutes);
  app.route('/api/best-execution/chain', bestExecutionChainRoutes);
  app.route('/api/carbon-registration/chain', carbonRegistrationChainRoutes);
  app.route('/api/covenant-certificate/chain', covenantCertificateChainRoutes);
  app.route('/api/tariff-indexation/chain', tariffIndexationChainRoutes);
  app.route('/api/compliance-inspection/chain', complianceInspectionChainRoutes);
  app.route('/api/problem-management/chain', problemManagementChainRoutes);
  app.route('/api/carbon-reversal/chain', carbonReversalChainRoutes);
  app.route('/api/tariff-determination/chain', tariffDeterminationChainRoutes);
  app.route('/api/trade-reporting/chain', tradeReportingChainRoutes);
  app.route('/api/loan-default/chain', loanDefaultChainRoutes);
  app.route('/api/curtailment-claim/chain', curtailmentClaimChainRoutes);
  app.route('/api/change-enablement/chain', changeEnablementChainRoutes);
  app.route('/api/carbon-offset-claim/chain', carbonOffsetClaimChainRoutes);
  app.route('/api/licence-application/chain', licenceApplicationChainRoutes);
  app.route('/api/reserve-activation/chain', reserveActivationChainRoutes);
  app.route('/api/availability-guarantee/chain', availabilityGuaranteeChainRoutes);
  app.route('/api/market-abuse/chain', marketAbuseChainRoutes);
  app.route('/api/credit-origination/chain', creditOriginationChainRoutes);
  app.route('/api/payment-security/chain', paymentSecurityChainRoutes);
  app.route('/api/security-remediation/chain', securityRemediationChainRoutes);
  app.route('/api/crediting-renewal/chain', creditingRenewalChainRoutes);
  app.route('/api/sseg-registration/chain', ssegRegistrationChainRoutes);
  app.route('/api/grid-capacity/chain', gridCapacityAllocationChainRoutes);
  app.route('/api/pm-compliance/chain', pmComplianceChainRoutes);
  app.route('/api/algo-cert/chain', algoCertChainRoutes);
  app.route('/api/loan-transfer/chain', loanTransferChainRoutes);
  app.route('/api/ppa-termination/chain', ppaTerminationChainRoutes);
  app.route('/api/warranty-recovery/chain', warrantyRecoveryChainRoutes);
  app.route('/api/permit-to-work/chain', permitToWorkChainRoutes);
  app.route('/api/carbon-erpa/chain', carbonErpaChainRoutes);
  app.route('/api/complaints/chain', complaintResolutionChainRoutes);
  app.route('/api/grid-code-compliance/chain', gridCodeComplianceChainRoutes);
  app.route('/api/counterparty-margin/chain', counterpartyMarginChainRoutes);
  app.route('/api/security-perfection/chain', securityPerfectionChainRoutes);
  app.route('/api/rec-lifecycle/chain', recLifecycleChainRoutes);
  app.route('/api/asset-prognostics/chain', assetPrognosticsChainRoutes);
  app.route('/api/spare-parts-provisioning/chain', sparePartsProvisioningChainRoutes);
  app.route('/api/poa-inclusion/chain', poaCpaInclusionChainRoutes);
  app.route('/api/levy-assessment/chain', levyAssessmentChainRoutes);
  app.route('/api/connection-energization/chain', connectionEnergizationChainRoutes);
  app.route('/api/trade-allocation/chain', tradeAllocationChainRoutes);
  app.route('/api/reserve-account/chain', reserveAccountChainRoutes);
  app.route('/api/ppa-change-in-law/chain', ppaChangeInLawChainRoutes);
  app.route('/api/generation-revenue-assurance/chain', generationRevenueAssuranceChainRoutes);
  app.route('/api/service-contract/chain', serviceContractChainRoutes);
  app.route('/api/ipp/change-order/chain', projectChangeOrderChainRoutes);
  app.route('/api/carbon-issuance/chain', carbonIssuanceChainRoutes);
  app.route('/api/consultation-notice/chain', consultationNoticeChainRoutes);
  app.route('/api/black-start/chain', blackStartChainRoutes);
  app.route('/api/settlement-fail/chain', settlementFailChainRoutes);
  app.route('/api/dscr-monitoring/chain', dscrMonitoringChainRoutes);
  app.route('/api/ppa-nomination/chain', ppaNominationChainRoutes);
  app.route('/api/bess-soh/chain', bessSohChainRoutes);
  app.route('/api/oem-fco/chain', oemFcoChainRoutes);
  app.route('/api/benchmark-transition/chain', benchmarkTransitionChainRoutes);
  app.route('/api/ccp-assessment/chain', ccpAssessmentChainRoutes);
  app.route('/api/ipp/project-risk/chain', projectRiskChainRoutes);
  app.route('/api/regulator/enforcement-action/chain', enforcementActionChainRoutes);
  app.route('/api/grid/rez-capacity/chain', rezCapacityChainRoutes);
  app.route('/api/lender/sll-kpi/chain', sllKpiChainRoutes);
  app.route('/api/ipp/submittal-rfi/chain', submittalRfiChainRoutes);
  app.route('/api/ipp/dfr/chain', dfrChainRoutes);
  app.route('/api/ipp/punch-list/chain', punchListChainRoutes);
  app.route('/api/ipp/itp/chain', itpChainRoutes);
  app.route('/api/ipp/handover-dossier/chain', handoverDossierChainRoutes);
  app.route('/api/offtaker/ppa-annual-recon/chain', ppaAnnualReconChainRoutes);
  app.route('/api/esums/soiling-audit/chain', soilingAuditChainRoutes);
  app.route('/api/carbon/esg-disclosure/chain', esgDisclosureChainRoutes);
  app.route('/api/support/service-request/chain', serviceRequestChainRoutes);
  app.route('/api/grid/imbalance-settlement/chain', imbalanceSettlementChainRoutes);
  app.route('/api/regulator/enforcement-action-s35/chain', enforcementActionS35ChainRoutes);
  app.route('/api/trader/pretrade-credit/chain', pretradeCreditChainRoutes);
  app.route('/api/lender/loan-restructure/chain', loanRestructureChainRoutes);
  app.route('/api/carbon/credit-rating/chain', carbonCreditRatingChainRoutes);
  app.route('/api/grid/transmission-outage/chain', transmissionOutageChainRoutes);
  app.route('/api/trader/pnl-attribution/chain', pnlAttributionChainRoutes);
  app.route('/api/ipp/wbs-schedule/chain', ippScheduleChainRoutes);
  app.route('/api/ipp/cost-evm/chain', ippEvmChainRoutes);
  app.route('/api/ipp/document-control/chain', ippDocumentControlChainRoutes);
  app.route('/api/ipp/submittals/chain', ippSubmittalRoute);
  app.route('/api/ipp/rfis/chain', ippRfiRoute);
  app.route('/api/ipp/change-orders/chain', ippChangeOrderRoute);
  app.route('/api/audit-chain', auditChainRoute);
  app.route('/api/regulator-exports', regulatorExportRoutes);
  app.route('/api/reconciliation-attestation', reconciliationAttestationRoutes);
  app.route('/api/control-environment-audit', controlEnvironmentAuditRoutes);
  app.route('/api/scada-connector', scadaConnectorRoutes);
  app.route('/api/mqtt-opcua-connector', mqttOpcuaConnectorRoutes);
  app.route('/api/strate-swift-connector', strateSwiftConnectorRoutes);
  app.route('/api/sap-oracle-erp-connector', sapOracleErpConnectorRoutes);
  app.route('/api/government-filing-connector', governmentFilingConnectorRoutes);
  app.route('/api/anomaly-detection-ml', anomalyDetectionMlRoutes);
  app.route('/api/rul-prediction-ml', rulPredictionMlRoutes);
  app.route('/api/fault-fingerprint-ml', faultFingerprintMlRoutes);
  app.route('/api/ntt-comparison-battery', nttComparisonBatteryRoutes);
  app.route('/api/stage-gate', stageGateRoutes);
  app.route('/api/ipp-issues', ippIssuesRoutes);
  app.route('/api/ipp-risk', ippRiskRoutes);
  app.route('/api/ipp-stakeholder', ippStakeholderRoutes);
  app.route('/api/ipp-lessons-learned', ippLessonsLearnedRoutes);
  app.route('/api/ipp-ncr', ippNcrRoutes);
  app.route('/api/ipp-method-statement', ippMethodStatementRoutes);
  app.route('/api/ipp-env-monitoring', ippEnvMonitoringRoutes);
  app.route('/api/ipp-mir', ippMirRoutes);
  app.route('/api/ipp-subcontractor', ippSubcontractorRoutes);
  app.route('/api/ipp-progress-claim', ippProgressClaimRoutes);
  app.route('/api/ipp-tq', ippTqRoutes);
  app.route('/api/ipp-diary', ippDiaryRoutes);
  app.route('/api/ipp-site-instruction', ippSiteInstructionRoutes);
  app.route('/api/ipp-dlp-defect', ippDlpDefectRoutes);
  app.route('/api/ipp-variation-order', ippVariationOrderRoutes);
  app.route('/api/ipp-payment-cert', ippPaymentCertRoutes);
  app.route('/api/ipp-final-completion', ippFinalCompletionRoutes);
  app.route('/api/ipp-om-handover', ippOmHandoverRoutes);
  app.route('/api/ipp-land-register', ippLandRegisterRoutes);
  app.route('/api/ipp-env-closure', ippEnvClosureRoutes);
  app.route('/api/ipp-commissioning-test', ippCommissioningTestRoutes);
  app.route('/api/ipp-ie-cert', ippIeCertRoutes);
  app.route('/api/ipp-tpa', ippTpaRoutes);
  app.route('/api/ipp-ppa-variation', ippPpaVariationRoutes);
  app.route('/api/ipp-change-of-control', ippChangeOfControlRoutes);
  app.route('/api/ipp-refinancing', ippRefinancingRoutes);
  app.route('/api/ipp-fm', ippFmRoutes);
  app.route('/api/ipp-annual-report', ippAnnualReportRoutes);
  app.route('/api/ipp-contractor-default', ippContractorDefaultRoutes);
  app.route('/api/ipp-eco-report', ippEcoReportRoutes);
  app.route('/api/ipp-lta-certificate', ippLtaCertificateRoutes);
  app.route('/api/ipp-land-amendment', ippLandAmendmentRoutes);
  app.route('/api/ipp-community-trust', ippCommunityTrustRoutes);
  app.route('/api/ipp-grid-compliance', ippGridComplianceRoutes);
  app.route('/api/ipp-ccc', ippCccRoutes);
  app.route('/api/ipp-om-contract', ippOmContractRoutes);
  app.route('/api/ipp-bfs', ippBfsRoutes);
  app.route('/api/ipp-ea-amendment', ippEaAmendmentRoutes);
  app.route('/api/ipp-wul', ippWulRoutes);
  app.route('/api/ipp-hra', ippHraRoutes);
  app.route('/api/ipp-ael', ippAelRoutes);
  app.route('/api/ipp-force-majeure', ippForceMajeureRoutes);
  app.route('/api/ipp-lc-reports', ippLcReportRoutes);
  app.route('/api/ipp-milestone-certs', ippMilestoneCertRoutes);
  app.route('/api/ipp-esmr', ippEsmrRoutes);
  app.route('/api/ipp-ie-annual-reviews', ippIeAnnualReviewRoutes);
  app.route('/api/ipp-insurance-renewals', ippInsuranceRenewalRoutes);
  app.route('/api/ipp-perf-securities', ippPerfSecurityRoutes);
  app.route('/api/ipp-cep-compliance', ippCepComplianceRoutes);
  app.route('/api/ipp-sed-compliance', ippSedComplianceRoutes);
  app.route('/api/ipp-bbbee-verification', ippBbbeeVerificationRoutes);
  app.route('/api/ipp-lender-reporting', ippLenderReportingRoutes);
  app.route('/api/ipp-licence-returns', ippLicenceReturnsRoutes);
  app.route('/api/ipp-reipppp-reports', ippReippppReportsRoutes);
  app.route('/api/ipp-equity-transfer', ippEquityTransferRoutes);
  app.route('/api/ipp-quarterly-gen-reports', ippQuarterlyGenReportRoutes);
  app.route('/api/ipp-annual-compliance-assessments', ippAnnualComplianceAssessmentRoutes);
  app.route('/api/ipp-annual-audits', ippAnnualAuditRoutes);
  app.route('/api/ipp-emp-compliance-reports', ippEmpComplianceReportRoutes);
  app.route('/api/ipp-cp-tracker', ippCpTrackerRoutes);
  app.route('/api/ipp-licence-obligations', ippLicenceObligationRoutes);
  app.route('/api/facility-amendments', facilityAmendmentRoutes);
  app.route('/api/esap-compliance', esapComplianceRoutes);
  app.route('/api/protection-relay-tests', protectionRelayRoutes);
  app.route('/api/unserved-energy-claims', unservedEnergyRoutes);
  app.route('/api/station-participant-links', stationParticipantLinkRoutes);
  app.route('/api/admin-platform', adminPlatformRoutes);
  app.route('/api/settlement-auto', settlementAutoRoutes);
  app.route('/api/imbalance', imbalanceRoutes);
  app.route('/api/data-tier', dataTierRoutes);
  app.route('/api/ai-briefs', aiBriefsRoutes);
  app.route('/api/realtime', realtimeRoutes);
  app.route('/api/siem', siemRoutes);
  app.route('/api/reports', reportsRoutes);
  app.route('/api/telemetry', telemetryRoutes);
  app.route('/api/lookup', lookupRoutes);
  app.route('/api/admin/monitoring', monitoringRoutes);
  app.route('/api/admin/revenue', adminRevenueRoutes);
  app.route('/api/admin/market-halt', adminMarketHaltRoutes);
  // Backup routes are deliberately mounted outside /api/admin to avoid being
  // shadowed by the admin sub-app's global authMiddleware.
  app.route('/api/backup', backupRoutes);
  app.route('/api/search', searchRoutes);
  app.route('/api/notifications', notificationsRoutes);
  app.route('/api/schedule', scheduleRoutes);
  app.route('/api/esums-portal-view', esumsOmPortalPublic);
  app.route('/api/esums-portal', esumsOmPortalAdmin);
  // Native device ingestion (per-site opaque ingest keys, NO user JWT).
  app.route('/api/esums-ingest', esumsIngestRoutes);
  app.route('/api/esums', esumsOmRoutes);
  app.route('/api/esums', esumsOmIntelRoutes);
  app.route('/api/esums', esumsOmAnalysisRoutes);
  app.route('/api/esums/data-sources', esumsDataSourcesRoutes);
  app.route('/api/esums/projects', esumsProjectsRoutes);
  app.route('/api/esums/solax', esumsOmSolaxRoutes);
  app.route('/api/esums/manufacturers', esumsManufacturersRoutes);
  app.route('/api/esums/accruals', esumsAccrualsRoutes);
  app.route('/api/esums/settlement-invoices', esumsInvoiceRoutes);
  app.route('/api/esums/carbon-credits', esumsCreditRoutes);
  // Public status page MUST be mounted BEFORE the catch-all platform router.
  app.route('/api/public/status', publicStatusRoutes);
  app.route('/api/public/status', statusDeepPub);
  app.route('/api/public/regulator', regulatorL5Pub);
  app.route('/api/public/audit',     auditL5Pub);
  app.route('/api/public/legal',     publicLegalRoutes);
  // Must be BEFORE /api (platformFeaturesRoutes) which has a blanket authMiddleware.
  app.route('/api/pdf',  pdfRoutes);
  app.route('/api/rbac', rbacRoutes);
  app.route('/api/mfa',         mfaRoutes);
  app.route('/api/kyc',         kycRoutes);
  app.route('/api/consent',     consentRoutes);
  app.route('/api/popia',       popiaSelfServiceRoutes);
  app.route('/api/regulator',   regulatorReportRoutes);
  // Depth additions
  app.route('/api/auth-deep',     authDeepRoutes);
  app.route('/api/kyc-deep',      kycDeepRoutes);
  app.route('/api/status-admin',  statusDeepAdmin);
  app.route('/api/popia-deep',    popiaDeepRoutes);
  app.route('/api/reports-deep',  reportsDeepRoutes);
  app.route('/api/trading-deep',    tradingDeepRoutes);
  app.route('/api/settlement-deep', settlementDeepRoutes);
  app.route('/api/ipp-deep',        ippDeepRoutes);
  app.route('/api/lender-deep',     lenderDeepRoutes);
  app.route('/api/carbon-deep',     carbonDeepRoutes);
  app.route('/api/grid-l5',         gridL5Routes);
  app.route('/api/regulator-l5',    regulatorL5Admin);
  app.route('/api/trading-clearing-l5', tradingClearingL5Routes);
  app.route('/api/audit-l5',            auditL5Admin);
  app.route('/api/marketplace-l5',      marketplaceL5Routes);
  app.route('/api/ai-assistant',        aiAssistantRoutes);
  app.route('/api/polish',              polishRoutes);
  app.route('/api/business-depth',      businessDepthRoutes);
  app.route('/api/bulk',                bulkOpsRoutes);
  app.route('/api/ux-state',            uxStateRoutes);
  app.route('/api/documents',           documentsRoutes);
  app.route('/api/print-packs',         printPacksRoutes);
  app.route('/api/onboarding', onboardingRoutes);
  app.route('/api/onboarding', onboardingChecklistRoutes);
  // Full static basePath so the /kyc segment wins over any /:param route in the
  // sibling onboarding routers (Hono silent-collision risk - deliberate).
  app.route('/api/onboarding/kyc', onboardingKycRoutes);
  app.route('/api/kyc-verifications', kycChainRoutes);
  app.route('/api/smart-meter-assets', smartMeterChainRoutes);
  app.route('/api/carbon-tax-returns', carbonTaxChainRoutes);
  app.route('/api/fsca-compliance-reports', fsccChainRoutes);
  app.route('/api/green-bond-reports', greenBondChainRoutes);
  app.route('/api/capital-adequacy-reports', capAdequacyChainRoutes);
  app.route('/api/slb-kpi-ratchets', slbKpiChainRoutes);
  app.route('/api/demand-response-events', demandResponseChainRoutes);
  app.route('/api/carbon-registry-transfers', carbonRegistryTransferChainRoutes);
  app.route('/api/milestone-variance-reports', milestoneVarianceChainRoutes);
  app.route('/api/csat-records', csatChainRoutes);
  app.route('/api/public-consultations', publicConsultationChainRoutes);
  app.route('/api/green-tariff-disclosures', greenTariffChainRoutes);
  app.route('/api/substation-assets', substationAssetChainRoutes);
  app.route('/api/dscr-reports', dscrReportChainRoutes);
  app.route('/api/methodology-amendments', methodologyAmendmentChainRoutes);
  app.route('/api/esap-monitoring', esapMonitoringChainRoutes);
  app.route('/api/eop-activations', eopActivationChainRoutes);
  app.route('/api/fsca-conduct-reports', fscaConductReportChainRoutes);
  app.route('/api/sla-performance-reports', slaPerformanceReportChainRoutes);
  app.route('/api/credit-insurance', creditInsuranceChainRoutes);
  app.route('/api/wheeling-access', wheelingAccessChainRoutes);
  app.route('/api/market-conduct-exams', marketConductExamChainRoutes);
  app.route('/api/export-curtailments', exportCurtailmentChainRoutes);
  app.route('/api/cross-border-trades', crossBorderTradeChainRoutes);
  app.route('/api/cp-clearances', cpClearanceChainRoutes);
  app.route('/api/gtia', gtiaChainRoutes);
  app.route('/api/carbon/scope3-disclosure/chain', scope3DisclosureChainRoutes);
  app.route('/api/carbon/vcm-projects', vcmProjectDevelopmentChainRoutes);
  app.route('/api/carbon/budget', carbonBudgetChainRoutes);
  app.route('/api/rec/device-registration', recDeviceRegistrationChainRoutes);
  app.route('/api/rec/issuance', recIssuanceChainRoutes);
  app.route('/api/vcm/order-book', vcmOrderBookRoutes);
  app.route('/api/sustainability/marketplace', sustainabilityMarketplaceRoutes);
  app.route('/api/sustainability/transactions', sustainabilityTransactionChainRoutes);
  app.route('/api/certificate-track/bundle', certBundleChainRoutes);
  app.route('/api/subscription/billing', subscriptionBillingChainRoutes);
  app.route('/api/offtaker/virtual-ppa-settlement', virtualPpaSettlementChainRoutes);
  app.route('/api/ipp/cbt-sed', cbtSedChainRoutes);
  app.route('/api/lender/construction-cost-report', constructionCostReportChainRoutes);
  app.route('/api/trader/isda-agreement', isdaAgreementChainRoutes);
  app.route('/api/admin/dsr', dataSubjectRequestChainRoutes);
  app.route('/api/grid/interconnector-schedule', interconnectorScheduleChainRoutes);
  // W7 National Dashboard — operator-only platform-wide aggregate view.
  app.route('/api/national-dashboard', nationalDashboardRoutes);
  // Meridian — computed per-role workspace aggregator over chain registry.
  app.route('/api/horizon', horizonRoutes);
  // Meridian — generic two-sided case view over chain registry.
  app.route('/api/thread', threadRoutes);
  // Meridian — generic per-chain list (KPI + filters + rows) over chain registry.
  app.route('/api/ledger', ledgerRoutes);
  // Generalized cross-role deal engine (offer→match→evaluate→accept→track).
  // A specific prefix must be registered BEFORE the broad /api catch-all so
  // Hono (which matches in registration order) routes it correctly.
  app.route('/api/deals', dealsRoutes);

  // platformFeaturesRoutes is the catch-all for /api — it must remain LAST.
  app.route('/api', platformFeaturesRoutes);
}
