// ═══════════════════════════════════════════════════════════════════════════
// Meridian generic journey matrix — every initiation chain, created through the
// deployed SPA, as Playwright tests generated from the registry fixture.
//
// WHY THIS IS ONE GENERIC SUITE, NOT 76 HAND-WRITTEN SPECS:
// Meridian is 100% registry-driven — every chain in MERIDIAN_CHAINS renders
// through the SAME four surfaces (Horizon / Atlas / Ledger / Thread). The
// green-bond canary (meridian-green-bond-canary.spec.ts) proved the full
// create→advance machine end-to-end through prod for ONE chain. This suite
// generalises that proof across ALL 76 chains that expose an `initiation` block,
// driving each create form through the real UI and recording the outcome.
//
// PER CHAIN (driven as the ADMIN persona — verified to hold ≥1 action on every
// one of the 76 initiation chains, and admin is in WRITE_ROLES + sees all lanes):
//   1. Deep-link to the Ledger:           /ledger/<key>           (LedgerPage)
//   2. Click the "+ New" button           (label = initiation.label, exact)
//   3. Fill the schema-driven FieldForm    (#ff-<key>, type-aware synthetic filler)
//   4. Submit; capture the create POST     (status + body recorded)
//   5. If created: deep-link to Thread     /thread/<key>/<id>
//   6. Fire the first valid no-field admin action (best-effort forward advance)
//   7. Record create/advance outcome into the journey matrix
//
// HARD vs SOFT (this is deliberate — the deliverable is a complete matrix, not a
// wall of red where most chains "need a real upstream FK"):
//   HARD (fails the chain's test):
//     • the "+ New" button never appears        → real UI gap
//     • the composer never opens                → real UI gap
//     • no create POST ever fires               → form could not be driven
//   SOFT (recorded, not failed here):
//     • create 4xx (validation / missing FK)    → flagged GAP for cross-role follow-on
//     • advance 422 (invalid-from-state)        → tried next action
//   A SINGLE trailing test asserts NO create returned 5xx (a server-side crash on
//   synthetic input is a genuine robustness bug worth surfacing as one clear red),
//   and prints the full matrix.
//
// IDENTIFIABLE PROD DATA: every row this suite writes carries the stamp
// E2E-CANARY-2026 in its first string field (and in every other string/evidence
// field) so prod rows are greppable and distinguishable from real data.
//
// RATE-LIMIT DISCIPLINE: reuse the global-setup ADMIN token (one login), seeded
// via localStorage + a mocked /auth/refresh — no per-test /api/auth/login.
// ═══════════════════════════════════════════════════════════════════════════

import { test, expect, type Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// ── Registry fixture (generated by scripts/build-journey-fixture.ts). Read
//    synchronously at module load so the data-driven test() calls exist before
//    Playwright collects the file. cwd is open-energy-platform/ when running. ──
type FieldSpec = { key: string; label: string; type: string; required: boolean; options: string[] | null; unit: string | null };
type ActionSpec = { action: string; label: string; path: string; method: string; roles: string[]; body: unknown; tone: string | null; fields: FieldSpec[] };
type ChainRow = {
  key: string; wave: number; title: string; table: string; statusCol: string;
  terminal: string[]; lanes: string[]; hasInitiation: boolean;
  initiation: { label: string; path: string; fields: FieldSpec[] } | null;
  actions: ActionSpec[];
};
const MATRIX_PATH = path.join(process.cwd(), 'tests', 'browser', 'fixtures', 'journey-matrix.json');
const matrix = JSON.parse(fs.readFileSync(MATRIX_PATH, 'utf8')) as { rows: ChainRow[] };
const INIT_CHAINS = matrix.rows.filter((r) => r.hasInitiation && r.initiation);

// Per-run suffix keeps the greppable E2E-CANARY-2026 prefix while making each run's
// synthetic keys unique — so a re-run doesn't 409 against rows a prior run created.
// RUN is pinned by global-setup (process.env.JOURNEY_RUN) so it stays STABLE across
// Playwright worker restarts — a test failure tears down the worker, re-imports this
// module, and would otherwise recompute RUN, orphaning the JSONL keys. Fallback to a
// fresh id only when run standalone without global-setup.
const RUN = process.env.JOURNEY_RUN || Date.now().toString(36);
const STAMP = `E2E-CANARY-2026-${RUN}`;
const RESULTS_PATH = path.join(process.cwd(), 'tests', 'browser', 'fixtures', 'journey-results.json');
// Durable append-only log. Each chain's outcome is appended here in its test's
// finally block, so the summary survives worker restarts (module-level RESULTS is
// wiped on every restart). global-setup clears this file once before workers spawn.
const RESULTS_JSONL = path.join(process.cwd(), 'tests', 'browser', 'fixtures', 'journey-results.jsonl');

// Forward-biased advance: try non-terminal verbs first so a synthetic case
// advances forward rather than being immediately rejected/cancelled/closed.
const DESTRUCTIVE = /reject|cancel|withdraw|abort|decline|terminate|write_off|writeoff|dismiss|refuse|revoke|void|fail|clawback|claw_back/i;

interface JourneyResult {
  key: string; wave: number; createStatus: number; created: boolean; id: string | null;
  advanced: boolean; advanceAction: string | null; advanceStatus: number; note: string;
}
const RESULTS: JourneyResult[] = [];

let SHARED_ADMIN_TOKEN: string | null = null;
let SHARED_ADMIN_USER: unknown = null;

const ADMIN_EMAIL = 'admin@openenergy.co.za';
const DEMO_PASSWORD = process.env.DEMO_PASSWORD || 'Demo@2024!';
// Re-mint the shared admin token when it has less than this much JWT life left.
// The suite is single-worker/serial (playwright.config: workers:1), so this is a
// safe place to refresh: at most ~once per ~50min, well inside the 10/5min login
// limiter. Without this, the 1h JWT freezes at suite start and the /auth/refresh
// mock keeps replaying it; a >1h run then 401s every late ledger GET and the +New
// button never renders (mis-recorded as a per-chain create failure).
const TOKEN_REFRESH_MARGIN_MS = 8 * 60 * 1000;

function tokenLifeMs(tok: string | null): number {
  if (!tok) return 0;
  try {
    const payload = JSON.parse(Buffer.from(tok.split('.')[1], 'base64').toString('utf8'));
    return (payload.exp ?? 0) * 1000 - Date.now();
  } catch {
    return 0;
  }
}

test.beforeAll(() => {
  const tok = process.env.PLAYWRIGHT_ADMIN_TOKEN;
  if (!tok) throw new Error('PLAYWRIGHT_ADMIN_TOKEN not set — global-setup may have failed');
  SHARED_ADMIN_TOKEN = tok;
  const userJson = process.env.PLAYWRIGHT_ADMIN_TOKEN_USER;
  if (userJson) { try { SHARED_ADMIN_USER = JSON.parse(userJson); } catch { /* fall back to real /auth/me */ } }
});

// Mint a fresh admin token when the shared one is near expiry. One real login,
// gated on remaining JWT life so it fires at most once per refresh window.
async function maybeRefreshToken(page: Page, baseURL?: string) {
  if (tokenLifeMs(SHARED_ADMIN_TOKEN) > TOKEN_REFRESH_MARGIN_MS) return;
  try {
    const url = `${baseURL ?? ''}/api/auth/login`;
    const r = await page.request.post(url, {
      data: { email: ADMIN_EMAIL, password: DEMO_PASSWORD },
      failOnStatusCode: false,
    });
    if (r.ok()) {
      const fresh = (await r.json())?.data?.token;
      if (fresh) SHARED_ADMIN_TOKEN = fresh;
    }
    // Non-ok (429/500): keep the old token — this chain may 401, but we tried,
    // and the next chain re-attempts once the limiter window drains.
  } catch {
    // Network error — keep the old token.
  }
}

async function seedToken(page: Page, baseURL?: string) {
  await maybeRefreshToken(page, baseURL);
  if (!SHARED_ADMIN_TOKEN) throw new Error('shared ADMIN token not initialised');
  const tokenValue = SHARED_ADMIN_TOKEN;
  // AuthContext bootstraps via an httpOnly cookie refresh that isn't available in
  // headless Playwright — intercept so it gets a valid token and authenticates.
  await page.route('**/api/auth/refresh', async (route) => {
    await route.fulfill({
      status: 200, contentType: 'application/json',
      body: JSON.stringify({ success: true, data: { token: tokenValue, expires_in: 3600 } }),
    });
  });
  // Mock /auth/me with the body captured once in global-setup so 76 navigations
  // don't each force a real round-trip (faster + avoids any session bounce).
  if (SHARED_ADMIN_USER) {
    const userBody = SHARED_ADMIN_USER;
    await page.route('**/api/auth/me', async (route) => {
      await route.fulfill({
        status: 200, contentType: 'application/json',
        body: JSON.stringify({ success: true, data: userBody }),
      });
    });
  }
  await page.addInitScript((tok) => { localStorage.setItem('token', tok as string); }, tokenValue);
}

// Type-aware synthetic filler. Fills EVERY string/evidence field with the canary
// stamp (greppability), and every REQUIRED non-string field with a plausible
// value of the right type. Required enums MUST be explicitly selected — the
// FieldForm <select> has a disabled "Select…" placeholder, so an unset required
// enum blocks submit (value === ''). Optional non-string fields are left blank to
// minimise spurious FK/validation rejections.
async function fillForm(composer: ReturnType<Page['locator']>, fields: FieldSpec[]) {
  let stamped = false;
  for (const f of fields) {
    const loc = composer.locator(`#ff-${f.key}`);
    if (f.type === 'boolean') continue; // checkbox default (false) is always "supplied"
    if (f.type === 'string') {
      if (!stamped) { await loc.fill(STAMP); stamped = true; }
      else if (f.required) await loc.fill(stringFor(f.key));
      continue;
    }
    if (f.type === 'evidence') { await loc.fill(`${STAMP} synthetic evidence`); continue; }
    if (!f.required) continue; // only fill required for number/date/enum
    if (f.type === 'enum') { if (f.options && f.options.length) await loc.selectOption(f.options[0]); }
    else if (f.type === 'number') await loc.fill('1000000');
    else if (f.type === 'date') await loc.fill('2026-12-31');
  }
}

// Other required strings get a key-aware but still canary-marked value so the row
// stays greppable while satisfying obvious format expectations where cheap.
function stringFor(key: string): string {
  if (/month|period/i.test(key)) return '2026-06';
  if (/year/i.test(key)) return '2026';
  return `E2E-CANARY-${key}-${RUN}`;
}

function isAdmin(a: ActionSpec): boolean { return (a.roles || []).includes('admin'); }

// ── One test per initiation chain. ───────────────────────────────────────────
for (const chain of INIT_CHAINS) {
  const init = chain.initiation!;
  test(`Meridian journey: ${chain.key} (W${chain.wave})`, async ({ page, baseURL }) => {
    test.setTimeout(90_000); // ledger load + create + thread + advance (advance is itself wall-clock bounded below)
    const r: JourneyResult = {
      key: chain.key, wave: chain.wave, createStatus: 0, created: false, id: null,
      advanced: false, advanceAction: null, advanceStatus: 0, note: '',
    };
    try {
      await seedToken(page, baseURL);

      // 1. Ledger surface.
      await page.goto(`${baseURL}/ledger/${chain.key}`, { waitUntil: 'load' });
      const newBtn = page.getByRole('button', { name: init.label, exact: true });
      await expect(newBtn, `"+ New" button (${init.label}) should render on /ledger/${chain.key}`)
        .toBeVisible({ timeout: 20_000 });

      // 2 & 3. Open composer, fill schema-driven form.
      await newBtn.click();
      const composer = page.getByRole('dialog', { name: init.label });
      await expect(composer, 'create composer should open').toBeVisible({ timeout: 10_000 });
      await fillForm(composer, init.fields);

      // 4. Submit; capture the create POST (whatever its status).
      const [createResp] = await Promise.all([
        page.waitForResponse(
          (resp) => resp.url().includes(init.path) && resp.request().method() === 'POST',
          { timeout: 25_000 },
        ),
        composer.getByRole('button', { name: init.label, exact: true }).click(),
      ]);
      r.createStatus = createResp.status();
      let body: any = null;
      try { body = await createResp.json(); } catch { /* non-JSON error body */ }
      if (r.createStatus >= 200 && r.createStatus < 300) {
        r.created = true;
        r.id = body?.data?.id ?? body?.id ?? null;
      } else {
        r.note = `create ${r.createStatus}: ${JSON.stringify(body?.error ?? body ?? '').slice(0, 200)}`;
      }

      // 5 & 6. Best-effort forward advance through the Thread. Fires the first
      //         admin action that the state machine accepts (2xx). Handles BOTH
      //         no-field actions (fire immediately) and field actions (open the
      //         schema-driven drawer, fill it, submit). Invalid-from-state returns
      //         409/422 — surfaced in the .act-error banner — so we try the next.
      if (r.created && r.id) {
        await page.goto(`${baseURL}/thread/${chain.key}/${r.id}`, { waitUntil: 'load' });
        // The actbar renders only after GET /api/thread/:chainKey/:id resolves and the
        // case body paints. Iterating candidates before that → every btn.count() is 0
        // and we fall through with advanceAction=null. Wait for the actbar (or give up
        // if this chain exposes no admin actions — footer is absent when t.actions=[]).
        await page.locator('.actbar-btns').first()
          .waitFor({ state: 'visible', timeout: 15_000 }).catch(() => {});
        // Forward verbs first; terminal/destructive verbs only if nothing else advances.
        const candidates = chain.actions.filter(isAdmin)
          .sort((a, b) => Number(DESTRUCTIVE.test(a.action)) - Number(DESTRUCTIVE.test(b.action)));
        // Wall-clock bound the advance loop. Chains with 13-14 actions × per-candidate
        // waits otherwise blow the test timeout mid-action → "Target page has been
        // closed" + a lost result. Bounding it here means we always exit cleanly,
        // record the outcome, and the create assertion still runs.
        const advanceDeadline = Date.now() + 30_000;
        for (const a of candidates) {
          if (Date.now() > advanceDeadline) { r.note += (r.note ? ' ' : '') + '[advance-timeout]'; break; }
          const btn = page.getByRole('button', { name: a.label, exact: true });
          if (!(await btn.count())) continue;
          const method = (a.method || 'POST').toUpperCase();
          const tail = a.path.replace('/api', '').replace(':id', r.id);
          const hasFields = !!(a.fields && a.fields.length);
          let aResp;
          try {
            if (hasFields) {
              // Click opens the action-form veil (no network yet); fill, then submit.
              await btn.first().click();
              const drawer = page.getByRole('dialog', { name: a.label });
              await expect(drawer).toBeVisible({ timeout: 5_000 });
              await fillForm(drawer, a.fields);
              [aResp] = await Promise.all([
                page.waitForResponse(
                  (resp) => resp.url().includes(tail) && resp.request().method() === method,
                  { timeout: 12_000 },
                ),
                drawer.getByRole('button', { name: a.label, exact: true }).click(),
              ]);
            } else {
              [aResp] = await Promise.all([
                page.waitForResponse(
                  (resp) => resp.url().includes(tail) && resp.request().method() === method,
                  { timeout: 12_000 },
                ),
                btn.first().click(),
              ]);
            }
          } catch {
            await page.keyboard.press('Escape'); // dismiss any open drawer, try next
            continue;
          }
          r.advanceStatus = aResp.status();
          r.advanceAction = a.action;
          if (aResp.status() >= 200 && aResp.status() < 300) { r.advanced = true; break; }
          // 409/422 = invalid-from-state — close the drawer (if any) and try the next.
          if (hasFields) await page.keyboard.press('Escape');
        }
      }
    } finally {
      RESULTS.push(r);
      // Durable: one JSON object per line. Survives worker restarts (a test failure
      // tears the worker down and wipes module-level RESULTS). The summary test reads
      // this file, not RESULTS, so the matrix is complete even with mid-run failures.
      try { fs.appendFileSync(RESULTS_JSONL, JSON.stringify(r) + '\n'); } catch { /* best-effort */ }
    }

    // HARD: the create POST must have fired with a real status, and must not be a
    // server-side crash. 4xx (validation / missing FK) is a SOFT gap, recorded above.
    expect(r.createStatus, `${chain.key}: create POST never fired or returned no status`).toBeGreaterThan(0);
    expect(r.createStatus, `${chain.key}: create POST 5xx — ${r.note}`).toBeLessThan(500);
  });
}

// ── Trailing aggregation: write the matrix, print it, assert no 5xx creates. ──
test('Meridian journey matrix — summary & 5xx gate', async () => {
  // Source of truth is the durable JSONL (survives worker restarts), NOT the
  // module-level RESULTS array — a single test failure restarts the worker and
  // wipes RESULTS, so relying on it alone yields a truncated matrix. Read every
  // appended line, last-wins per key (a re-tried chain overwrites its earlier row),
  // then union with whatever this worker holds in memory as a belt-and-braces.
  const byKey = new Map<string, JourneyResult>();
  try {
    const raw = fs.readFileSync(RESULTS_JSONL, 'utf8');
    for (const ln of raw.split('\n')) {
      const t = ln.trim();
      if (!t) continue;
      try { const r = JSON.parse(t) as JourneyResult; byKey.set(r.key, r); } catch { /* skip partial line */ }
    }
  } catch { /* no JSONL — fall back to in-memory only */ }
  for (const r of RESULTS) if (!byKey.has(r.key)) byKey.set(r.key, r);

  // Sort for a stable, readable report.
  const sorted = [...byKey.values()].sort((a, b) => a.wave - b.wave || a.key.localeCompare(b.key));
  const created = sorted.filter((r) => r.created);
  const advanced = sorted.filter((r) => r.advanced);
  const gaps = sorted.filter((r) => !r.created && r.createStatus > 0 && r.createStatus < 500);
  const serverErrors = sorted.filter((r) => r.createStatus >= 500);

  const report = {
    generatedAgainst: process.env.BASE || 'https://oe.vantax.co.za',
    total: sorted.length,
    created: created.length,
    advanced: advanced.length,
    gaps: gaps.length,
    serverErrors: serverErrors.length,
    rows: sorted,
  };
  fs.writeFileSync(RESULTS_PATH, JSON.stringify(report, null, 2));

  const line = (r: JourneyResult) =>
    `  ${r.created ? '✓' : (r.createStatus >= 500 ? '✗' : '⚠')} W${r.wave} ${r.key.padEnd(34)} ` +
    `create=${r.createStatus} ${r.advanced ? `advanced(${r.advanceAction})` : (r.advanceStatus ? `adv=${r.advanceStatus}` : '')}` +
    `${r.note ? ` — ${r.note}` : ''}`;
  console.log(
    `\n══ Meridian journey matrix (${report.created}/${report.total} created, ` +
    `${report.advanced} advanced, ${report.gaps} gaps, ${report.serverErrors} server-errors) ══\n` +
    sorted.map(line).join('\n') + '\n',
  );

  expect(
    serverErrors.map((r) => `${r.key} → ${r.createStatus} ${r.note}`),
    'no initiation chain create should return 5xx on synthetic input',
  ).toEqual([]);
});
