// pages/src/meridian/surfaces/esumsom/CarbonCreditsSurface.tsx
//
// Meridian surface — "Carbon credits" (esco / esums_owner O&M role). Extracted verbatim from the
// `carbon_credits` tab body of the retired EsumsOmPage SuitePage husk (E2.2). Self-contained:
// it renders a single-tab SuitePage so the inline SuiteTable behaviour (columns, currency/date
// formatting, StatusPill, rowActions) is preserved identically. Registered as `esco:carbon-credits`
// in surfaces.tsx and reached from Atlas (⌘K) via the roleData feature key `carbon_credits`.
import React from 'react';
import { SuitePage, StatusPill, TabSpec } from '../../../components/SuitePage';

export default function CarbonCreditsSurface(_props: { role: string }) {
  const tabs: TabSpec[] = [
    {
      key: 'carbon_credits',
      label: 'Carbon credits',
      endpoint: '/esums/carbon-credits',
      description: 'Monthly carbon credit records auto-minted from the accruals ledger. Each record represents one tCO₂e-equivalent offset generated by a station in a calendar month. Actions: verify (provisional → verified) then retire (verified → retired) to permanently retire against a carbon-tax liability or Scope-2 claim.',
      columns: [
        { key: 'station_name',   label: 'Station' },
        { key: 'period_start',   label: 'Period',    date: true },
        { key: 'kwh_generated',  label: 'kWh',       align: 'right', number: true },
        { key: 'carbon_tco2e',   label: 'tCO₂e',     align: 'right', number: true },
        { key: 'carbon_value_zar', label: 'Value (R)',align: 'right', currency: true },
        { key: 'status',         label: 'Status', render: (r) => <StatusPill status={String(r.status)} /> },
        { key: 'registry_ref',   label: 'Registry ref' },
        { key: 'retired_at',     label: 'Retired',   date: true },
      ],
      rowActions: [
        { label: 'Verify', tone: 'primary', endpoint: '/esums/carbon-credits/{id}', method: 'PATCH',
          form: { title: 'Verify carbon credit', endpoint: '', extraBody: { action: 'verify' }, fields: [] as any }},
        { label: 'Retire', tone: 'danger', endpoint: '/esums/carbon-credits/{id}', method: 'PATCH',
          form: { title: 'Retire carbon credit', endpoint: '', extraBody: { action: 'retire' }, fields: [
            { name: 'notes', type: 'textarea', label: 'Retirement purpose / beneficiary', required: true },
          ] as any}},
      ],
    },
  ];
  return (
    <SuitePage
      eyebrow="Esums · Operations"
      title="Carbon credits"
      subtitle="Monthly carbon credits auto-minted from the accruals ledger."
      tabs={tabs}
      initialTab="carbon_credits"
      aiBriefAccent={{ from: '#1e3a5f', to: '#336a38' }}
    />
  );
}
