-- ════════════════════════════════════════════════════════════════════════
-- 035 · trader schema gaps — superseded by 036/037
--
-- HISTORICAL NOTE: this migration originally tried to (a) add `order_type`
-- to trade_orders and (b) create placeholder `trade_fills`, `credit_limits`
-- and `mark_prices` tables. Each of those operations conflicts with an
-- earlier or later migration:
--
--   • order_type      — already added by 020 (matching engine).
--   • trade_fills     — already created by 020 with a different schema;
--                       the placeholder index referencing `participant_id`
--                       fails because 020's schema lacks that column.
--   • credit_limits   — already created by 022 (trader risk).
--   • mark_prices     — already created by 022.
--
-- Migration 036 then DROPs and recreates trade_fills + credit_limits with
-- the correct shape, and 037 does the same for mark_prices. So everything
-- this migration tried to do is delivered correctly by 020/022/036/037.
--
-- The conflicting statements have been removed so a fresh database can
-- replay the full migration sequence without aborting at 035. The file
-- is preserved (rather than deleted) so the d1_migrations tracker still
-- finds it on production deployments.
-- ════════════════════════════════════════════════════════════════════════

-- intentionally empty
