-- W146: IPP Variation Order Management
-- JBCC 6.2 Cl.38-39 + NEC4 Cl.60-62
-- INVERTED SLA: larger value = more review time
-- SIGNATURE: refer_adjudication crosses regulator EVERY tier

CREATE TABLE IF NOT EXISTS oe_ipp_variation_orders (
  id                        TEXT PRIMARY KEY,
  participant_id            TEXT NOT NULL,
  project_id                TEXT NOT NULL,
  title                     TEXT NOT NULL,
  description               TEXT,
  variation_type            TEXT NOT NULL CHECK(variation_type IN (
                              'scope_change','time_extension','cost_adjustment',
                              'design_change','statutory_change','provisional_sum')),
  value_tier                TEXT NOT NULL CHECK(value_tier IN (
                              'minor','moderate','significant','major','material')),
  instructed_value_zar      REAL,
  agreed_value_zar          REAL,
  issued_by                 TEXT,
  site_ref                  TEXT,
  quotation_notes           TEXT,
  chain_status              TEXT NOT NULL DEFAULT 'instructed' CHECK(chain_status IN (
                              'instructed','acknowledged','quotation_submitted','quotation_reviewed',
                              'approved','rejected','in_progress','completed_pending_payment',
                              'paid','disputed_pricing','adjudicated','cancelled')),
  sla_due_at                TEXT,
  sla_breached              INTEGER NOT NULL DEFAULT 0,
  -- per-state timestamps
  instructed_at             TEXT,
  acknowledged_at           TEXT,
  quotation_submitted_at    TEXT,
  quotation_reviewed_at     TEXT,
  approved_at               TEXT,
  rejected_at               TEXT,
  completed_at              TEXT,
  paid_at                   TEXT,
  adjudicated_at            TEXT,
  cancelled_at              TEXT,
  created_at                TEXT NOT NULL,
  updated_at                TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ippvo_participant ON oe_ipp_variation_orders(participant_id);
CREATE INDEX IF NOT EXISTS idx_ippvo_project ON oe_ipp_variation_orders(project_id);
CREATE INDEX IF NOT EXISTS idx_ippvo_status ON oe_ipp_variation_orders(chain_status);
CREATE INDEX IF NOT EXISTS idx_ippvo_tier ON oe_ipp_variation_orders(value_tier);
CREATE INDEX IF NOT EXISTS idx_ippvo_sla ON oe_ipp_variation_orders(sla_due_at) WHERE sla_breached = 0;

-- Seed: 12 variation orders across value tiers for the NXT participant (IPP demo)
INSERT OR IGNORE INTO oe_ipp_variation_orders VALUES
  ('ippvo_001','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Additional earthworks for transformer bay','Soil conditions required 800m³ extra excavation',
   'scope_change','moderate',385000,NULL,'pa_001','EW-VO-001',NULL,
   'instructed',datetime('now','+14 days'),0,
   datetime('now','-20 days'),datetime('now','-19 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-20 days'),datetime('now','-19 days')),
  ('ippvo_002','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Cable route redesign — rocky substrate','Approved cable route found impassable',
   'design_change','significant',750000,780000,'pa_001','CR-VO-002',NULL,
   'approved',datetime('now','+5 days'),0,
   datetime('now','-35 days'),datetime('now','-34 days'),datetime('now','-30 days'),datetime('now','-28 days'),datetime('now','-25 days'),NULL,NULL,NULL,NULL,NULL,
   datetime('now','-35 days'),datetime('now','-25 days')),
  ('ippvo_003','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'EOT 45 days — civil works delays','Adverse weather + supplier strike',
   'time_extension','minor',0,NULL,'pa_001','EOT-VO-003',NULL,
   'quotation_submitted',datetime('now','+3 days'),0,
   datetime('now','-15 days'),datetime('now','-14 days'),datetime('now','-10 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-15 days'),datetime('now','-10 days')),
  ('ippvo_004','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Grid connection upgrade — 33kV to 66kV','Eskom connection voltage revised upward',
   'statutory_change','major',3200000,NULL,'pa_001','GC-VO-004',NULL,
   'disputed_pricing',datetime('now','-2 days'),1,
   datetime('now','-50 days'),datetime('now','-49 days'),datetime('now','-44 days'),datetime('now','-40 days'),NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-50 days'),datetime('now','-40 days')),
  ('ippvo_005','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Steel structure supply PC sum instruction','Instruction to purchase structural steel from approved supplier',
   'provisional_sum','significant',620000,618000,'pa_001','SS-VO-005',NULL,
   'paid',NULL,0,
   datetime('now','-90 days'),datetime('now','-89 days'),datetime('now','-85 days'),datetime('now','-82 days'),datetime('now','-78 days'),NULL,datetime('now','-40 days'),datetime('now','-20 days'),NULL,NULL,
   datetime('now','-90 days'),datetime('now','-20 days')),
  ('ippvo_006','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Access road surface upgrade','Gravel to tar as required by heavy equipment',
   'scope_change','moderate',290000,285000,'pa_001','AR-VO-006',NULL,
   'in_progress',datetime('now','+8 days'),0,
   datetime('now','-60 days'),datetime('now','-59 days'),datetime('now','-55 days'),datetime('now','-52 days'),datetime('now','-48 days'),NULL,NULL,NULL,NULL,NULL,
   datetime('now','-60 days'),datetime('now','-48 days')),
  ('ippvo_007','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'SCADA system specification change','NERSA mandated updated cybersecurity standard',
   'statutory_change','moderate',180000,NULL,'pa_001','SC-VO-007',NULL,
   'quotation_reviewed',datetime('now','+1 days'),0,
   datetime('now','-25 days'),datetime('now','-24 days'),datetime('now','-20 days'),datetime('now','-18 days'),NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-25 days'),datetime('now','-18 days')),
  ('ippvo_008','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Omission: on-site water storage tank','Design change removed 50kL tank',
   'scope_change','minor',-45000,-45000,'pa_001','OS-VO-008',NULL,
   'paid',NULL,0,
   datetime('now','-120 days'),datetime('now','-119 days'),datetime('now','-116 days'),datetime('now','-113 days'),datetime('now','-110 days'),NULL,datetime('now','-70 days'),datetime('now','-50 days'),NULL,NULL,
   datetime('now','-120 days'),datetime('now','-50 days')),
  ('ippvo_009','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Substation protection relay upgrade','Required by Eskom grid code amendment 2025',
   'design_change','significant',540000,NULL,'pa_001','PR-VO-009',NULL,
   'acknowledged',datetime('now','+18 days'),0,
   datetime('now','-5 days'),datetime('now','-4 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-5 days'),datetime('now','-4 days')),
  ('ippvo_010','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Concrete mix design change — saline soil','Marine-grade concrete required for foundations near wetland',
   'scope_change','moderate',320000,NULL,'pa_001','CC-VO-010',NULL,
   'rejected',NULL,0,
   datetime('now','-70 days'),datetime('now','-69 days'),datetime('now','-65 days'),datetime('now','-62 days'),NULL,datetime('now','-58 days'),NULL,NULL,NULL,NULL,
   datetime('now','-70 days'),datetime('now','-58 days')),
  ('ippvo_011','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'HV transformer procurement — change to Tier 1 supplier','Standard supplier delivery 18-month lead time',
   'cost_adjustment','major',2800000,NULL,'pa_001','HV-VO-011',NULL,
   'adjudicated',NULL,0,
   datetime('now','-100 days'),datetime('now','-99 days'),datetime('now','-93 days'),datetime('now','-89 days'),NULL,NULL,NULL,NULL,datetime('now','-30 days'),NULL,
   datetime('now','-100 days'),datetime('now','-30 days')),
  ('ippvo_012','id_7c352b86da89907a85266a250e15db95','proj_nxt_solar_001',
   'Emergency culvert reinstatement after flash flood','Unforeseeable weather event damage',
   'scope_change','significant',680000,NULL,'pa_001','CU-VO-012',NULL,
   'completed_pending_payment',datetime('now','+10 days'),0,
   datetime('now','-45 days'),datetime('now','-44 days'),datetime('now','-40 days'),datetime('now','-37 days'),datetime('now','-33 days'),NULL,datetime('now','-5 days'),NULL,NULL,NULL,
   datetime('now','-45 days'),datetime('now','-5 days'));
