-- W150: IPP As-Built Survey & Land Register Update
-- Deeds Registries Act 47/1937 + NERSA Grid Code §C-5 + SPLUMA 16/2013
-- INVERTED SLA: larger plant footprint = more erven/servitudes = more time
-- SIGNATURE: lodge_deeds crosses regulator EVERY tier; reject_survey crosses major/material

CREATE TABLE IF NOT EXISTS oe_ipp_land_register (
  id                      TEXT PRIMARY KEY,
  participant_id          TEXT NOT NULL,
  project_id              TEXT NOT NULL,
  area_ha                 REAL NOT NULL,
  area_tier               TEXT NOT NULL CHECK(area_tier IN ('minor','moderate','significant','major','material')),
  erf_count               INTEGER,
  servitude_count         INTEGER,
  surveyor_firm           TEXT,
  deeds_reference         TEXT,
  description             TEXT,
  chain_status            TEXT NOT NULL DEFAULT 'survey_commissioned' CHECK(chain_status IN (
                            'survey_commissioned','field_survey','diagram_drafted',
                            'sg_approved','servitude_notarised','deeds_lodged',
                            'deeds_registered','defective_title','survey_rejected',
                            'abandoned','superseded')),
  sla_due_at              TEXT,
  sla_breached            INTEGER NOT NULL DEFAULT 0,
  field_survey_at         TEXT,
  diagram_submitted_at    TEXT,
  sg_approved_at          TEXT,
  servitude_notarised_at  TEXT,
  deeds_lodged_at         TEXT,
  deeds_registered_at     TEXT,
  defective_title_at      TEXT,
  rejected_at             TEXT,
  created_at              TEXT NOT NULL,
  updated_at              TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ipplr_participant ON oe_ipp_land_register(participant_id);
CREATE INDEX IF NOT EXISTS idx_ipplr_project ON oe_ipp_land_register(project_id);
CREATE INDEX IF NOT EXISTS idx_ipplr_status ON oe_ipp_land_register(chain_status);
CREATE INDEX IF NOT EXISTS idx_ipplr_sla ON oe_ipp_land_register(sla_due_at) WHERE sla_breached = 0;

-- Seed: 12 land register items across tiers and stages
INSERT INTO oe_ipp_land_register VALUES
  ('ipplr_001','demo_ipp_001','ip_004',
   620,'major',8,14,'GeoSurvey Associates (Pty) Ltd','T12345/2025',
   'De Aar 75MW — 620ha; 8 erven; 14 servitudes (power line + access road + pipeline)',
   'deeds_registered',NULL,0,
   datetime('now','-120 days'),datetime('now','-110 days'),datetime('now','-95 days'),datetime('now','-80 days'),datetime('now','-65 days'),datetime('now','-45 days'),NULL,NULL,
   datetime('now','-130 days'),datetime('now','-45 days')),
  ('ipplr_002','demo_ipp_001','proj_nxt_solar_001',
   185,'significant',3,6,'Mokhele Surveyors CC',NULL,
   '20MW PV — 185ha; 3 erven; 6 servitudes (grid connection + access)',
   'deeds_lodged',datetime('now','+15 days'),0,
   datetime('now','-45 days'),datetime('now','-35 days'),datetime('now','-22 days'),datetime('now','-10 days'),datetime('now','-3 days'),NULL,NULL,NULL,
   datetime('now','-50 days'),datetime('now','-3 days')),
  ('ipplr_003','demo_ipp_001','proj_nxt_solar_001',
   95,'significant',2,4,'Mokhele Surveyors CC',NULL,
   '10MW carport — 95ha; 2 erven; 4 servitudes',
   'servitude_notarised',datetime('now','+20 days'),0,
   datetime('now','-30 days'),datetime('now','-22 days'),datetime('now','-15 days'),datetime('now','-5 days'),NULL,NULL,NULL,NULL,
   datetime('now','-35 days'),datetime('now','-5 days')),
  ('ipplr_004','demo_ipp_001','ip_004',
   1200,'material',15,28,'Land Surveys SA (Pty) Ltd',NULL,
   '200MW Wind — 1200ha; 15 erven; 28 servitudes (transmission + access + borrow pits)',
   'sg_approved',datetime('now','+50 days'),0,
   datetime('now','-25 days'),datetime('now','-18 days'),datetime('now','-8 days'),NULL,NULL,NULL,NULL,NULL,
   datetime('now','-30 days'),datetime('now','-8 days')),
  ('ipplr_005','demo_ipp_001','ip_004',
   380,'major',5,10,'GeoSurvey Associates (Pty) Ltd',NULL,
   '100MW Wind Phase 2 — 380ha; SG diagram submitted for approval',
   'diagram_drafted',datetime('now','+60 days'),0,
   datetime('now','-15 days'),datetime('now','-8 days'),NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-20 days'),datetime('now','-8 days')),
  ('ipplr_006','demo_ipp_001','proj_nxt_solar_001',
   55,'significant',1,3,'Ntuli Land Surveyors',NULL,
   '15MW agri-solar — field survey in progress; drone mapping complete',
   'field_survey',datetime('now','+45 days'),0,
   datetime('now','-5 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-7 days'),datetime('now','-5 days')),
  ('ipplr_007','demo_ipp_001','proj_nxt_solar_001',
   30,'moderate',1,2,'Ntuli Land Surveyors',NULL,
   '5MW C&I rooftop — survey commissioned; surveyor appointed',
   'survey_commissioned',datetime('now','+42 days'),0,
   NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-2 days'),datetime('now','-2 days')),
  ('ipplr_008','demo_ipp_001','ip_004',
   280,'major',4,8,'Land Surveys SA (Pty) Ltd',NULL,
   '80MW solar storage — defective title raised: missing notarial bond on Erf 3',
   'defective_title',datetime('now','-5 days'),1,
   datetime('now','-80 days'),datetime('now','-70 days'),datetime('now','-55 days'),datetime('now','-40 days'),datetime('now','-25 days'),NULL,datetime('now','-10 days'),NULL,
   datetime('now','-85 days'),datetime('now','-10 days')),
  ('ipplr_009','demo_ipp_001','ip_004',
   450,'major',6,12,'GeoSurvey Associates (Pty) Ltd','T08891/2024',
   '150MW HVDC — registered; title deed issued; all servitudes endorsed',
   'deeds_registered',NULL,0,
   datetime('now','-200 days'),datetime('now','-185 days'),datetime('now','-165 days'),datetime('now','-145 days'),datetime('now','-120 days'),datetime('now','-90 days'),NULL,NULL,
   datetime('now','-210 days'),datetime('now','-90 days')),
  ('ipplr_010','demo_ipp_001','proj_nxt_solar_001',
   12,'moderate',1,2,'Mokhele Surveyors CC',NULL,
   'Survey rejected: SG diagram error — beacon co-ordinates transposed',
   'survey_rejected',NULL,0,
   datetime('now','-40 days'),datetime('now','-32 days'),datetime('now','-25 days'),NULL,NULL,NULL,NULL,datetime('now','-15 days'),
   datetime('now','-45 days'),datetime('now','-15 days')),
  ('ipplr_011','demo_ipp_001','proj_nxt_solar_001',
   8,'minor',1,1,'Ntuli Land Surveyors',NULL,
   '500kW rooftop — small footprint; SG approved, servitude pending notarisation',
   'sg_approved',datetime('now','+18 days'),0,
   datetime('now','-20 days'),datetime('now','-14 days'),datetime('now','-8 days'),NULL,NULL,NULL,NULL,NULL,
   datetime('now','-25 days'),datetime('now','-8 days')),
  ('ipplr_012','demo_ipp_001','ip_004',
   2100,'material',22,45,'Land Surveys SA (Pty) Ltd',NULL,
   '500MW CSP — 2100ha; 22 erven; 45 servitudes; commissioned; field survey commences next month',
   'survey_commissioned',datetime('now','+115 days'),0,
   NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-1 days'),datetime('now','-1 days'));
