-- W151: IPP Environmental Compliance Closure & NEMA Closure Certificate
-- NEMA 107/1998 §24G + EIA Regulations 2014 (GN R982) + DFFE
-- INVERTED SLA: larger disturbed area = more regulatory scrutiny = more time
-- SIGNATURE: issue_closure_cert crosses regulator EVERY tier (environmental COD gate)

CREATE TABLE IF NOT EXISTS oe_ipp_env_closure (
  id                      TEXT PRIMARY KEY,
  participant_id          TEXT NOT NULL,
  project_id              TEXT NOT NULL,
  disturbed_area_ha       REAL NOT NULL,
  area_tier               TEXT NOT NULL CHECK(area_tier IN ('minor','moderate','significant','major','material')),
  eia_category            TEXT CHECK(eia_category IN ('basic_assessment','scoping_eir','amendments','exemption')),
  ea_reference            TEXT,
  emp_reference           TEXT,
  auditor_firm            TEXT,
  closure_cert_reference  TEXT,
  description             TEXT,
  chain_status            TEXT NOT NULL DEFAULT 'emp_audit_initiated' CHECK(chain_status IN (
                            'emp_audit_initiated','site_inspection','audit_report_drafted',
                            'stakeholder_review','remediation_required','remediation_complete',
                            'closure_recommended','nema_submission','nema_review',
                            'closure_issued','rejected','withdrawn')),
  sla_due_at              TEXT,
  sla_breached            INTEGER NOT NULL DEFAULT 0,
  inspection_started_at   TEXT,
  audit_report_at         TEXT,
  stakeholder_review_at   TEXT,
  remediation_required_at TEXT,
  remediation_complete_at TEXT,
  closure_recommended_at  TEXT,
  nema_submitted_at       TEXT,
  nema_review_at          TEXT,
  closure_issued_at       TEXT,
  rejected_at             TEXT,
  withdrawn_at            TEXT,
  created_at              TEXT NOT NULL,
  updated_at              TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ippec_participant ON oe_ipp_env_closure(participant_id);
CREATE INDEX IF NOT EXISTS idx_ippec_project ON oe_ipp_env_closure(project_id);
CREATE INDEX IF NOT EXISTS idx_ippec_status ON oe_ipp_env_closure(chain_status);
CREATE INDEX IF NOT EXISTS idx_ippec_sla ON oe_ipp_env_closure(sla_due_at) WHERE sla_breached = 0;

-- Seed: 12 env closure records across tiers and stages
INSERT INTO oe_ipp_env_closure VALUES
  ('ippec_001','demo_ipp_001','ip_004',
   620,'major','scoping_eir','EA/NW/2023/001','EMP-NW-75MW-2023',
   'ERM Southern Africa (Pty) Ltd','NEMA-CLO-2024-0341',
   'De Aar 75MW — 620ha disturbed; SRK EIR; EMP audited; NEMA closure cert issued',
   'closure_issued',NULL,0,
   datetime('now','-90 days'),datetime('now','-75 days'),datetime('now','-60 days'),NULL,NULL,datetime('now','-45 days'),datetime('now','-35 days'),datetime('now','-20 days'),datetime('now','-5 days'),NULL,NULL,
   datetime('now','-100 days'),datetime('now','-5 days')),
  ('ippec_002','demo_ipp_001','proj_nxt_solar_001',
   185,'significant','basic_assessment','EA/GP/2024/088','EMP-GP-20MW-2024',
   'Zutari (Pty) Ltd',NULL,
   '20MW PV — 185ha; basic assessment; EMP audit in progress; stakeholder review open',
   'stakeholder_review',datetime('now','+10 days'),0,
   datetime('now','-40 days'),datetime('now','-30 days'),datetime('now','-15 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-45 days'),datetime('now','-15 days')),
  ('ippec_003','demo_ipp_001','proj_nxt_solar_001',
   95,'significant','basic_assessment','EA/GP/2024/112',NULL,
   'Zutari (Pty) Ltd',NULL,
   '10MW carport — 95ha; non-conformances identified; remediation plan submitted',
   'remediation_required',datetime('now','+20 days'),0,
   datetime('now','-25 days'),datetime('now','-18 days'),datetime('now','-10 days'),datetime('now','-3 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-30 days'),datetime('now','-3 days')),
  ('ippec_004','demo_ipp_001','ip_004',
   1200,'material','scoping_eir','EA/NC/2022/007','EMP-NC-200MW-2022',
   'SRK Consulting (SA) (Pty) Ltd',NULL,
   '200MW Wind — 1200ha; full EIR; remediation complete; awaiting closure recommendation',
   'remediation_complete',datetime('now','+55 days'),0,
   datetime('now','-50 days'),datetime('now','-42 days'),datetime('now','-30 days'),datetime('now','-20 days'),datetime('now','-10 days'),NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-60 days'),datetime('now','-10 days')),
  ('ippec_005','demo_ipp_001','ip_004',
   380,'major','scoping_eir','EA/NC/2023/033',NULL,
   'ERM Southern Africa (Pty) Ltd',NULL,
   '100MW Wind Phase 2 — 380ha; EIR; closure recommended; NEMA submission prepared',
   'closure_recommended',datetime('now','+40 days'),0,
   datetime('now','-35 days'),datetime('now','-28 days'),datetime('now','-20 days'),NULL,NULL,datetime('now','-8 days'),NULL,NULL,NULL,NULL,NULL,
   datetime('now','-40 days'),datetime('now','-8 days')),
  ('ippec_006','demo_ipp_001','proj_nxt_solar_001',
   55,'significant','basic_assessment','EA/MP/2024/055',NULL,
   'Terratest Environmental',NULL,
   '15MW agri-solar — 55ha; site inspection underway; drone survey complete',
   'site_inspection',datetime('now','+50 days'),0,
   datetime('now','-5 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-8 days'),datetime('now','-5 days')),
  ('ippec_007','demo_ipp_001','proj_nxt_solar_001',
   12,'moderate','basic_assessment',NULL,NULL,
   'Terratest Environmental',NULL,
   '2MW C&I — 12ha; EMP compliance audit initiated; auditor appointed',
   'emp_audit_initiated',datetime('now','+44 days'),0,
   NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-1 days'),datetime('now','-1 days')),
  ('ippec_008','demo_ipp_001','ip_004',
   280,'major','scoping_eir','EA/NC/2022/019','EMP-NC-80MW-2022',
   'Golder Associates Africa (Pty) Ltd',NULL,
   '80MW solar storage — 280ha; EIR; under NEMA review; pending closure cert',
   'nema_review',datetime('now','+8 days'),0,
   datetime('now','-70 days'),datetime('now','-60 days'),datetime('now','-48 days'),NULL,NULL,datetime('now','-30 days'),datetime('now','-20 days'),datetime('now','-5 days'),NULL,NULL,NULL,
   datetime('now','-75 days'),datetime('now','-5 days')),
  ('ippec_009','demo_ipp_001','ip_004',
   450,'major','scoping_eir','EA/LP/2021/004','EMP-LP-150MW-2021',
   'SRK Consulting (SA) (Pty) Ltd','NEMA-CLO-2023-0178',
   '150MW HVDC — 450ha; full EIR; NEMA closure cert issued; post-closure monitoring active',
   'closure_issued',NULL,0,
   datetime('now','-180 days'),datetime('now','-165 days'),datetime('now','-148 days'),NULL,NULL,datetime('now','-130 days'),datetime('now','-115 days'),datetime('now','-95 days'),datetime('now','-70 days'),NULL,NULL,
   datetime('now','-190 days'),datetime('now','-70 days')),
  ('ippec_010','demo_ipp_001','proj_nxt_solar_001',
   8,'minor','exemption','EA/GP/2024/221',NULL,
   'Independent EA Practitioner',NULL,
   'Small rooftop — 8ha; exemption application; audit report drafted; rejected by DFFE',
   'rejected',NULL,0,
   datetime('now','-30 days'),datetime('now','-22 days'),datetime('now','-15 days'),NULL,NULL,datetime('now','-8 days'),datetime('now','-4 days'),datetime('now','-2 days'),NULL,datetime('now','-1 days'),NULL,
   datetime('now','-35 days'),datetime('now','-1 days')),
  ('ippec_011','demo_ipp_001','proj_nxt_solar_001',
   3,'minor','basic_assessment',NULL,NULL,
   'Independent EA Practitioner',NULL,
   '500kW rooftop — 3ha; EMP audit; audit report submitted; stakeholder review period ending',
   'stakeholder_review',datetime('now','+25 days'),0,
   datetime('now','-15 days'),datetime('now','-10 days'),datetime('now','-5 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-18 days'),datetime('now','-5 days')),
  ('ippec_012','demo_ipp_001','ip_004',
   2100,'material','scoping_eir','EA/NC/2020/002','EMP-NC-500MW-2020',
   'ERM Southern Africa (Pty) Ltd',NULL,
   '500MW CSP — 2100ha; full EIR; NEMA submission prepared; closure process imminent',
   'nema_submission',datetime('now','+90 days'),0,
   datetime('now','-40 days'),datetime('now','-33 days'),datetime('now','-25 days'),NULL,NULL,datetime('now','-15 days'),datetime('now','-5 days'),NULL,NULL,NULL,NULL,
   datetime('now','-45 days'),datetime('now','-5 days'));
