-- W152: IPP Commissioning Test Protocol & Performance Certificate
-- IEC 61724-1 + NERSA Grid Code §C-5 + REIPPPP Schedule 12; PAC/FAC framework
-- INVERTED SLA: larger plant capacity = longer test = more time
-- SIGNATURE: issue_performance_cert crosses regulator EVERY tier (COD prerequisite)

CREATE TABLE IF NOT EXISTS oe_ipp_commissioning_test (
  id                          TEXT PRIMARY KEY,
  participant_id              TEXT NOT NULL,
  project_id                  TEXT NOT NULL,
  capacity_mw                 REAL NOT NULL,
  capacity_tier               TEXT NOT NULL CHECK(capacity_tier IN ('minor','moderate','significant','major','material')),
  test_category               TEXT CHECK(test_category IN ('string_iv_test','ac_performance_test','protection_relay_test','grid_compliance_test','full_commissioning')),
  contractor_firm             TEXT,
  ie_firm                     TEXT,
  cert_reference              TEXT,
  description                 TEXT,
  chain_status                TEXT NOT NULL DEFAULT 'test_plan_submitted' CHECK(chain_status IN (
                                'test_plan_submitted','witness_inspection','hold_point_open','hold_point_cleared',
                                'performance_test_running','punch_list_issued','punch_list_cleared',
                                'pac_recommended','pac_issued','performance_test_running_post_pac',
                                'fac_recommended','performance_cert_issued','test_failed','withdrawn')),
  sla_due_at                  TEXT,
  sla_breached                INTEGER NOT NULL DEFAULT 0,
  witness_inspection_at       TEXT,
  hold_point_opened_at        TEXT,
  hold_point_cleared_at       TEXT,
  performance_test_started_at TEXT,
  punch_list_issued_at        TEXT,
  punch_list_cleared_at       TEXT,
  pac_issued_at               TEXT,
  performance_cert_issued_at  TEXT,
  test_failed_at              TEXT,
  created_at                  TEXT NOT NULL,
  updated_at                  TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ippct_participant ON oe_ipp_commissioning_test(participant_id);
CREATE INDEX IF NOT EXISTS idx_ippct_project ON oe_ipp_commissioning_test(project_id);
CREATE INDEX IF NOT EXISTS idx_ippct_status ON oe_ipp_commissioning_test(chain_status);
CREATE INDEX IF NOT EXISTS idx_ippct_sla ON oe_ipp_commissioning_test(sla_due_at) WHERE sla_breached = 0;

-- Seed: 12 commissioning test records across tiers and PAC/FAC stages
INSERT INTO oe_ipp_commissioning_test VALUES
  ('ippct_001','demo_ipp_001','ip_004',
   75,'major','full_commissioning','SORO Construction (Pty) Ltd','WSP Advisory SA',
   'PERF-CERT-2024-0341',
   'De Aar 75MW — full commissioning incl. protection relay, AC performance, grid compliance; cert issued',
   'performance_cert_issued',NULL,0,
   datetime('now','-80 days'),NULL,NULL,datetime('now','-65 days'),NULL,NULL,datetime('now','-50 days'),datetime('now','-20 days'),NULL,
   datetime('now','-90 days'),datetime('now','-20 days')),
  ('ippct_002','demo_ipp_001','proj_nxt_solar_001',
   20,'significant','ac_performance_test','WBHO Construction Ltd','Aurecon SA (Pty) Ltd',
   NULL,
   '20MW PV — AC performance test; PAC issued; post-PAC final performance test running',
   'performance_test_running_post_pac',datetime('now','+12 days'),0,
   datetime('now','-35 days'),NULL,NULL,datetime('now','-25 days'),NULL,NULL,datetime('now','-10 days'),NULL,NULL,
   datetime('now','-40 days'),datetime('now','-10 days')),
  ('ippct_003','demo_ipp_001','proj_nxt_solar_001',
   10,'significant','grid_compliance_test','WBHO Construction Ltd','Aurecon SA (Pty) Ltd',
   NULL,
   '10MW carport — grid compliance test; punch list items raised; contractor resolving',
   'punch_list_issued',datetime('now','+20 days'),0,
   datetime('now','-20 days'),NULL,NULL,datetime('now','-12 days'),datetime('now','-3 days'),NULL,NULL,NULL,NULL,
   datetime('now','-25 days'),datetime('now','-3 days')),
  ('ippct_004','demo_ipp_001','ip_004',
   200,'material','full_commissioning','Consolidated Power Projects','SRK Consulting (SA) (Pty) Ltd',
   NULL,
   '200MW Wind — full commissioning; hold point open for protection relay sign-off',
   'hold_point_open',datetime('now','+55 days'),0,
   datetime('now','-15 days'),datetime('now','-5 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-20 days'),datetime('now','-5 days')),
  ('ippct_005','demo_ipp_001','ip_004',
   100,'material','full_commissioning','Consolidated Power Projects','WSP Advisory SA',
   NULL,
   '100MW Wind Phase 2 — commissioning underway; AC performance test started',
   'performance_test_running',datetime('now','+45 days'),0,
   datetime('now','-25 days'),NULL,NULL,datetime('now','-10 days'),NULL,NULL,NULL,NULL,NULL,
   datetime('now','-30 days'),datetime('now','-10 days')),
  ('ippct_006','demo_ipp_001','proj_nxt_solar_001',
   15,'significant','string_iv_test','Solar Capital O&M','Zutari (Pty) Ltd',
   NULL,
   '15MW agri-solar — string IV test plan submitted; witness inspection scheduled',
   'witness_inspection',datetime('now','+38 days'),0,
   datetime('now','-2 days'),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-4 days'),datetime('now','-2 days')),
  ('ippct_007','demo_ipp_001','proj_nxt_solar_001',
   2,'minor','ac_performance_test','Local EPC Contractor',NULL,
   NULL,
   '2MW C&I — test plan submitted; awaiting witness inspection',
   'test_plan_submitted',datetime('now','+20 days'),0,
   NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-1 days'),datetime('now','-1 days')),
  ('ippct_008','demo_ipp_001','ip_004',
   80,'major','full_commissioning','SORO Construction (Pty) Ltd','Aurecon SA (Pty) Ltd',
   NULL,
   '80MW solar storage — PAC recommended; IE reviewing for PAC issuance',
   'pac_recommended',datetime('now','+20 days'),0,
   datetime('now','-40 days'),NULL,NULL,datetime('now','-28 days'),datetime('now','-18 days'),datetime('now','-12 days'),NULL,NULL,NULL,
   datetime('now','-45 days'),datetime('now','-12 days')),
  ('ippct_009','demo_ipp_001','ip_004',
   150,'major','full_commissioning','Murray & Roberts Cementation','SRK Consulting (SA) (Pty) Ltd',
   'PERF-CERT-2023-0178',
   '150MW HVDC — all tests passed; FAC recommended; performance cert issued',
   'performance_cert_issued',NULL,0,
   datetime('now','-160 days'),NULL,NULL,datetime('now','-140 days'),NULL,NULL,datetime('now','-120 days'),datetime('now','-60 days'),NULL,
   datetime('now','-170 days'),datetime('now','-60 days')),
  ('ippct_010','demo_ipp_001','proj_nxt_solar_001',
   5,'moderate','protection_relay_test','EPC Small Projects CC',NULL,
   NULL,
   'Protection relay test — failed: relay coordination error; contractor to rectify',
   'test_failed',NULL,0,
   datetime('now','-25 days'),NULL,NULL,datetime('now','-18 days'),NULL,NULL,NULL,NULL,datetime('now','-5 days'),
   datetime('now','-30 days'),datetime('now','-5 days')),
  ('ippct_011','demo_ipp_001','proj_nxt_solar_001',
   3,'minor','ac_performance_test','Local EPC Contractor',NULL,
   NULL,
   '500kW rooftop — punch list cleared; PAC recommended pending IE review',
   'pac_recommended',datetime('now','+15 days'),0,
   datetime('now','-18 days'),NULL,NULL,datetime('now','-12 days'),datetime('now','-8 days'),datetime('now','-4 days'),NULL,NULL,NULL,
   datetime('now','-20 days'),datetime('now','-4 days')),
  ('ippct_012','demo_ipp_001','ip_004',
   500,'material','full_commissioning','Consolidated Power Projects','Aurecon SA (Pty) Ltd',
   NULL,
   '500MW CSP — hold point cleared; full performance test starting; NERSA witnessing',
   'performance_test_running',datetime('now','+85 days'),0,
   datetime('now','-10 days'),datetime('now','-8 days'),datetime('now','-6 days'),datetime('now','-2 days'),NULL,NULL,NULL,NULL,NULL,
   datetime('now','-12 days'),datetime('now','-2 days'));
