-- W153: IPP Independent Engineer (IE) Milestone Certification
-- REIPPPP PPA Schedule 5 + LMA IE role + NERSA §C-5 milestone requirements
-- INVERTED SLA: larger disbursement milestone = more IE scrutiny = more time
-- SIGNATURE: issue_cert crosses regulator EVERY tier (drawdown notifiable; COD prerequisite)

CREATE TABLE IF NOT EXISTS oe_ipp_ie_cert (
  id                    TEXT PRIMARY KEY,
  participant_id        TEXT NOT NULL,
  project_id            TEXT NOT NULL,
  milestone_value_zar   REAL NOT NULL,
  milestone_tier        TEXT NOT NULL CHECK(milestone_tier IN ('minor','moderate','significant','major','material')),
  milestone_category    TEXT CHECK(milestone_category IN ('financial_close','construction_start','pac','cod','fac','loan_drawdown')),
  ie_firm               TEXT,
  lender_reference      TEXT,
  cert_number           TEXT,
  description           TEXT,
  chain_status          TEXT NOT NULL DEFAULT 'cert_request_submitted' CHECK(chain_status IN (
                          'cert_request_submitted','ie_site_visit','draft_report',
                          'borrower_review','comments_raised','comments_resolved',
                          'cert_issued','cert_rejected','withdrawn')),
  sla_due_at            TEXT,
  sla_breached          INTEGER NOT NULL DEFAULT 0,
  site_visit_at         TEXT,
  draft_report_at       TEXT,
  borrower_review_at    TEXT,
  comments_raised_at    TEXT,
  comments_resolved_at  TEXT,
  cert_issued_at        TEXT,
  rejected_at           TEXT,
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ippie_participant ON oe_ipp_ie_cert(participant_id);
CREATE INDEX IF NOT EXISTS idx_ippie_project ON oe_ipp_ie_cert(project_id);
CREATE INDEX IF NOT EXISTS idx_ippie_status ON oe_ipp_ie_cert(chain_status);
CREATE INDEX IF NOT EXISTS idx_ippie_sla ON oe_ipp_ie_cert(sla_due_at) WHERE sla_breached = 0;

-- Seed: 12 IE certification records across milestone types, tiers, and stages
INSERT OR IGNORE INTO oe_ipp_ie_cert VALUES
  ('ippie_001','demo_ipp_001','ip_004',
   850000000,'material','financial_close','WSP Advisory SA','LEC-2022-FC-001',
   'IE-CERT-2022-001',
   'De Aar 75MW — R850M financial close certification; IE confirmed all CP conditions met',
   'cert_issued',NULL,0,
   datetime('now','-400 days'),datetime('now','-390 days'),datetime('now','-382 days'),datetime('now','-376 days'),datetime('now','-373 days'),datetime('now','-368 days'),NULL,
   datetime('now','-410 days'),datetime('now','-368 days')),
  ('ippie_002','demo_ipp_001','ip_004',
   320000000,'major','pac','WSP Advisory SA','LEC-2022-FC-001',
   'IE-CERT-2024-PAC-01',
   'De Aar 75MW — R320M PAC milestone certification; IE confirmed practical completion',
   'cert_issued',NULL,0,
   datetime('now','-60 days'),datetime('now','-52 days'),datetime('now','-44 days'),datetime('now','-38 days'),NULL,NULL,datetime('now','-32 days'),
   datetime('now','-65 days'),datetime('now','-32 days')),
  ('ippie_003','demo_ipp_001','proj_nxt_solar_001',
   180000000,'major','pac','Aurecon SA (Pty) Ltd','NBF-2024-001',
   NULL,
   '20MW PV — R180M PAC certification; draft report under borrower review',
   'borrower_review',datetime('now','+5 days'),0,
   datetime('now','-18 days'),datetime('now','-12 days'),datetime('now','-6 days'),datetime('now','-2 days'),NULL,NULL,NULL,
   datetime('now','-22 days'),datetime('now','-2 days')),
  ('ippie_004','demo_ipp_001','proj_nxt_solar_001',
   80000000,'major','construction_start','Aurecon SA (Pty) Ltd','NBF-2024-001',
   'IE-CERT-2024-CS-01',
   '20MW PV — R80M construction start certification; IE confirmed all CP conditions',
   'cert_issued',NULL,0,
   datetime('now','-120 days'),datetime('now','-114 days'),datetime('now','-108 days'),datetime('now','-103 days'),NULL,NULL,datetime('now','-100 days'),
   datetime('now','-125 days'),datetime('now','-100 days')),
  ('ippie_005','demo_ipp_001','ip_004',
   1200000000,'material','financial_close','SRK Consulting (SA) (Pty) Ltd','DFI-2023-FC-001',
   'IE-CERT-2023-FC-001',
   '200MW Wind — R1.2B financial close; IE certified all conditions precedent satisfied',
   'cert_issued',NULL,0,
   datetime('now','-300 days'),datetime('now','-290 days'),datetime('now','-280 days'),datetime('now','-275 days'),datetime('now','-272 days'),datetime('now','-270 days'),NULL,
   datetime('now','-310 days'),datetime('now','-268 days')),
  ('ippie_006','demo_ipp_001','ip_004',
   450000000,'material','pac','SRK Consulting (SA) (Pty) Ltd','DFI-2023-FC-001',
   NULL,
   '200MW Wind — R450M PAC certification; comments raised by lender on turbine output',
   'comments_raised',datetime('now','+12 days'),0,
   datetime('now','-22 days'),datetime('now','-15 days'),datetime('now','-8 days'),datetime('now','-4 days'),datetime('now','-1 days'),NULL,NULL,
   datetime('now','-25 days'),datetime('now','-1 days')),
  ('ippie_007','demo_ipp_001','proj_nxt_solar_001',
   35000000,'significant','loan_drawdown','Aurecon SA (Pty) Ltd','NBF-2024-001',
   NULL,
   'Drawdown 3 — R35M; IE site visit underway; progress at 45%',
   'ie_site_visit',datetime('now','+14 days'),0,
   datetime('now','-3 days'),NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-5 days'),datetime('now','-3 days')),
  ('ippie_008','demo_ipp_001','ip_004',
   720000000,'material','cod','WSP Advisory SA','LEC-2022-FC-001',
   'IE-CERT-2024-COD-01',
   'De Aar 75MW — R720M COD certification; IE certified commercial operation date',
   'cert_issued',NULL,0,
   datetime('now','-30 days'),datetime('now','-24 days'),datetime('now','-18 days'),datetime('now','-14 days'),NULL,NULL,datetime('now','-10 days'),
   datetime('now','-35 days'),datetime('now','-10 days')),
  ('ippie_009','demo_ipp_001','ip_004',
   600000000,'material','fac','WSP Advisory SA','LEC-2022-FC-001',
   NULL,
   'De Aar 75MW — R600M FAC certification; cert request submitted',
   'cert_request_submitted',datetime('now','+44 days'),0,
   NULL,NULL,NULL,NULL,NULL,NULL,NULL,
   datetime('now','-1 days'),datetime('now','-1 days')),
  ('ippie_010','demo_ipp_001','proj_nxt_solar_001',
   15000000,'moderate','loan_drawdown','Zutari (Pty) Ltd','NBF-2024-001',
   'IE-CERT-2024-DRW-02',
   'Drawdown 2 — R15M; cert issued; progress certified at 25%',
   'cert_issued',NULL,0,
   datetime('now','-55 days'),datetime('now','-50 days'),datetime('now','-45 days'),datetime('now','-42 days'),NULL,NULL,datetime('now','-40 days'),
   datetime('now','-58 days'),datetime('now','-40 days')),
  ('ippie_011','demo_ipp_001','proj_nxt_solar_001',
   2500000,'minor','loan_drawdown','Zutari (Pty) Ltd','NBF-2024-001',
   NULL,
   'Drawdown 1 — R2.5M; cert rejected: insufficient progress evidence',
   'cert_rejected',NULL,0,
   datetime('now','-90 days'),datetime('now','-86 days'),datetime('now','-82 days'),datetime('now','-79 days'),datetime('now','-77 days'),NULL,NULL,
   datetime('now','-92 days'),datetime('now','-76 days')),
  ('ippie_012','demo_ipp_001','ip_004',
   3000000000,'material','financial_close','Aurecon SA (Pty) Ltd','CSP-DFI-2024-FC',
   NULL,
   '500MW CSP — R3B financial close; draft IE report under preparation',
   'draft_report',datetime('now','+38 days'),0,
   datetime('now','-8 days'),datetime('now','-3 days'),NULL,NULL,NULL,NULL,NULL,
   datetime('now','-12 days'),datetime('now','-3 days'));
