-- W154: IPP Third-Party Access & Wheeling Agreement
-- ERA §22 + NERSA Grid Code §C-2 + Eskom TPA Guidelines
-- INVERTED SLA: larger wheeling capacity = more commercial complexity = more time
-- SIGNATURE: sign_tpa_agreement crosses regulator EVERY tier (wheeling activation notifiable)

CREATE TABLE IF NOT EXISTS oe_ipp_tpa (
  id                    TEXT PRIMARY KEY,
  participant_id        TEXT NOT NULL,
  project_id            TEXT NOT NULL,
  wheeling_capacity_mw  REAL NOT NULL,
  capacity_tier         TEXT NOT NULL CHECK(capacity_tier IN ('minor','moderate','significant','major','material')),
  tpa_category          TEXT CHECK(tpa_category IN ('eskom_transmission','eskom_distribution','municipality','private_network')),
  network_owner         TEXT,
  offtaker_reference    TEXT,
  agreement_reference   TEXT,
  description           TEXT,
  chain_status          TEXT NOT NULL DEFAULT 'tpa_application_submitted' CHECK(chain_status IN (
                          'tpa_application_submitted','network_owner_review','technical_assessment',
                          'commercial_terms_proposed','negotiation_in_progress','terms_agreed',
                          'tpa_agreement_signed','wheeling_active',
                          'application_rejected','appeal_filed','appeal_determined','withdrawn')),
  sla_due_at            TEXT,
  sla_breached          INTEGER NOT NULL DEFAULT 0,
  tpa_signed_at         TEXT,
  wheeling_activated_at TEXT,
  rejected_at           TEXT,
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ipptpa_participant ON oe_ipp_tpa(participant_id);
CREATE INDEX IF NOT EXISTS idx_ipptpa_project ON oe_ipp_tpa(project_id);
CREATE INDEX IF NOT EXISTS idx_ipptpa_status ON oe_ipp_tpa(chain_status);
CREATE INDEX IF NOT EXISTS idx_ipptpa_sla ON oe_ipp_tpa(sla_due_at) WHERE sla_breached = 0;

-- Seed: 12 TPA records across tiers, network owners, and stages
INSERT INTO oe_ipp_tpa VALUES
  ('ipptpa_001','demo_ipp_001','ip_004',
   75,'major','eskom_transmission','Eskom Transmission — NW Region','PPA-OFFTAKE-2024-001',
   'TPA-NW-2024-0341',
   'De Aar 75MW — Eskom transmission TPA; wheeling 500km to Cape Town off-taker; active',
   'wheeling_active',NULL,0,
   datetime('now','-180 days'),datetime('now','-165 days'),NULL,
   datetime('now','-190 days'),datetime('now','-100 days')),
  ('ipptpa_002','demo_ipp_001','proj_nxt_solar_001',
   20,'significant','eskom_distribution','Eskom Distribution — GP','OFT-NBF-2024-001',
   NULL,
   '20MW PV — Eskom Distribution TPA; negotiation in progress on wheeling tariff',
   'negotiation_in_progress',datetime('now','+15 days'),0,
   NULL,NULL,NULL,
   datetime('now','-45 days'),datetime('now','-10 days')),
  ('ipptpa_003','demo_ipp_001','proj_nxt_solar_001',
   10,'significant','municipality','City of Johannesburg — Network Services','OFT-2024-COJ',
   NULL,
   '10MW carport — CoJ wheeling; commercial terms under negotiation',
   'commercial_terms_proposed',datetime('now','+30 days'),0,
   NULL,NULL,NULL,
   datetime('now','-28 days'),datetime('now','-5 days')),
  ('ipptpa_004','demo_ipp_001','ip_004',
   200,'material','eskom_transmission','Eskom Transmission — National','DFI-OFFTAKE-2023-001',
   NULL,
   '200MW Wind — R1.2B project; national transmission TPA; technical assessment underway',
   'technical_assessment',datetime('now','+65 days'),0,
   NULL,NULL,NULL,
   datetime('now','-55 days'),datetime('now','-20 days')),
  ('ipptpa_005','demo_ipp_001','ip_004',
   100,'material','eskom_transmission','Eskom Transmission — National','DFI-OFFTAKE-2023-001',
   'TPA-NAT-2023-0178',
   '150MW HVDC — national TPA; signed and wheeling active for 3 years',
   'wheeling_active',NULL,0,
   datetime('now','-400 days'),datetime('now','-380 days'),NULL,
   datetime('now','-410 days'),datetime('now','-310 days')),
  ('ipptpa_006','demo_ipp_001','proj_nxt_solar_001',
   15,'significant','municipality','eThekwini Municipality',NULL,
   NULL,
   '15MW agri-solar — eThekwini TPA; application submitted; network owner review starting',
   'network_owner_review',datetime('now','+50 days'),0,
   NULL,NULL,NULL,
   datetime('now','-8 days'),datetime('now','-3 days')),
  ('ipptpa_007','demo_ipp_001','proj_nxt_solar_001',
   2,'minor','municipality','Nelson Mandela Bay Municipality',NULL,
   NULL,
   '2MW C&I — NMB municipality TPA application submitted',
   'tpa_application_submitted',datetime('now','+29 days'),0,
   NULL,NULL,NULL,
   datetime('now','-1 days'),datetime('now','-1 days')),
  ('ipptpa_008','demo_ipp_001','ip_004',
   80,'major','eskom_distribution','Eskom Distribution — LP',NULL,
   NULL,
   '80MW solar storage — Limpopo wheeling; terms agreed; awaiting TPA signature',
   'terms_agreed',datetime('now','+10 days'),0,
   NULL,NULL,NULL,
   datetime('now','-75 days'),datetime('now','-5 days')),
  ('ipptpa_009','demo_ipp_001','ip_004',
   60,'major','eskom_transmission','Eskom Transmission — EC',NULL,
   NULL,
   '100MW Wind Phase 2 — Eskom rejected TPA application; appeal filed to NERSA',
   'appeal_filed',datetime('now','-5 days'),1,
   NULL,NULL,datetime('now','-20 days'),
   datetime('now','-90 days'),datetime('now','-20 days')),
  ('ipptpa_010','demo_ipp_001','proj_nxt_solar_001',
   5,'moderate','private_network','Transnet — Industrial Siding Network',NULL,
   NULL,
   'Private wheeling for industrial off-taker; TPA signed; wheeling operational',
   'wheeling_active',NULL,0,
   datetime('now','-120 days'),datetime('now','-110 days'),NULL,
   datetime('now','-125 days'),datetime('now','-78 days')),
  ('ipptpa_011','demo_ipp_001','proj_nxt_solar_001',
   8,'moderate','municipality','Steve Tshwete Local Municipality',NULL,
   NULL,
   'C&I wheeling application — municipality commenced technical assessment',
   'technical_assessment',datetime('now','+35 days'),0,
   NULL,NULL,NULL,
   datetime('now','-20 days'),datetime('now','-8 days')),
  ('ipptpa_012','demo_ipp_001','ip_004',
   500,'material','eskom_transmission','Eskom Transmission — National','CSP-OFT-2024',
   NULL,
   '500MW CSP — national TPA; application just submitted to Eskom',
   'tpa_application_submitted',datetime('now','+119 days'),0,
   NULL,NULL,NULL,
   datetime('now','-1 days'),datetime('now','-1 days'));
