-- ═══════════════════════════════════════════════════════════════════════
-- 519_seed_expert_persona_roster.sql
-- Demo seed: the 58-persona expert roster from CEC_PERSONA_CATALOGUE.md.
--
-- DEMO-ONLY. Targets open-energy-db (demo). NEVER run against live
-- cec-energy-db (prod, read-only).
--
-- Each persona is seeded under its CLOSEST EXISTING auth role (the role CHECK
-- in participants only admits the 11 production roles; SQLite can't ALTER a
-- CHECK without a full table rebuild). The INTENDED sub-role / function from
-- the catalogue (risk_officer, mrv_verifier, ghg_quant, grid_dispatcher,
-- security_agent, regulator_economist, sre, ml_ops, …) is carried verbatim in
-- job_title so the roster is fully descriptive without touching the schema.
-- Standing up those sub-roles as real auth roles is a separate Tier-1 backlog
-- item (CEC_PERSONA_CATALOGUE.md Part 3) — not a seeding prerequisite.
--
-- password_hash reuses the shared demo hash (password Demo@2024!, static
-- salt) so every persona logs in like the 11 base demo accounts.
--
-- ponytail: INSERT OR IGNORE — idempotent (re-run = no-op). Ceiling: edits to
-- a persona row won't re-apply on re-run; bump to ON CONFLICT DO UPDATE only
-- if these become editable seed records.
-- ═══════════════════════════════════════════════════════════════════════

-- ── Facet A — Power Trading, Settlement & Clearing, Market Risk ──────────
INSERT OR IGNORE INTO participants
  (id, email, password_hash, name, company_name, role, status, kyc_status, bbbee_level, subscription_tier, tenant_id, email_verified, onboarding_completed, phone, job_title, org_website, org_reg_num, bio, created_at, updated_at)
VALUES
 ('persona_a1','thandeka.mokoena@mkhizetraders.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Thandeka Mokoena','Mkhize Energy Traders','trader','active','approved',1,'enterprise','default',1,1,'+27 83 410 2271','Head of Power Trading','https://www.mkhizetraders.co.za','2014/118734/07','Owns desk P&L and risk appetite across all energy types and delivery days. CFA charterholder, FSCA-registered FAIS representative, 15 years across SAPP bilateral and day-ahead books.',datetime('now'),datetime('now')),
 ('persona_a2','sipho.naidoo@mkhizetraders.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Sipho Naidoo','Mkhize Energy Traders','trader','active','approved',2,'enterprise','default',1,1,'+27 82 661 9043','Power Trader / Market Maker','https://www.mkhizetraders.co.za','2014/118734/07','Quotes two-sided prices and runs the intraday book within limits and market-making obligations. 9 years on the continuous market; FSCA-registered representative.',datetime('now'),datetime('now')),
 ('persona_a3','riaan.vandermerwe@quantflux.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Riaan van der Merwe','QuantFlux Trading','trader','active','approved',3,'professional','default',1,1,'+27 84 220 7715','Quant / Algo Developer (intended: algo_engineer)','https://www.quantflux.co.za','2018/204417/07','Builds, certifies and operates automated strategies with kill-switch governance under FMA/FSCA RTS6-equivalent controls. MSc Financial Engineering; 8 years in systematic trading.',datetime('now'),datetime('now')),
 ('persona_a4','lerato.dlamini@mkhizetraders.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Lerato Dlamini','Mkhize Energy Traders','trader','active','approved',1,'enterprise','default',1,1,'+27 83 775 6620','Market Risk Officer (intended: risk_officer)','https://www.mkhizetraders.co.za','2014/118734/07','Independently measures and constrains market risk; sets the limits the desk trades within. FRM charterholder; runs VaR, scenario and limit-utilisation oversight.',datetime('now'),datetime('now')),
 ('persona_a5','pravesh.govind@mkhizetraders.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Pravesh Govind','Mkhize Energy Traders','trader','active','approved',2,'enterprise','default',1,1,'+27 82 339 8841','Middle-Office Settlement Analyst (intended: middle_office)','https://www.mkhizetraders.co.za','2014/118734/07','Takes matched trades through clearing, margin and atomic DvP to confirmed cash and energy. 11 years in post-trade operations; expert in CPMI-IOSCO settlement discipline.',datetime('now'),datetime('now')),
 ('persona_a6','ayesha.patel@nersa.org.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Ayesha Patel','NERSA','regulator','active','approved',1,'enterprise','default',1,1,'+27 83 504 1192','Market Surveillance Officer','https://www.nersa.org.za','2005/009127/07','Detects, investigates and reports market abuse; owns the STOR pipeline under FMA Chapter X. 12 years in market conduct and surveillance.',datetime('now'),datetime('now')),
 ('persona_a7','johan.botha@clearco.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Johan Botha','ClearCo Central Counterparty','admin','active','approved',2,'enterprise','default',1,1,'+27 82 916 4408','Clearing & Margin Manager (CCP)','https://www.clearco.co.za','2016/118730/07','Guarantees settlement: margin gate, counterparty waterfall and default management under CPMI-IOSCO PFMI. 14 years in clearing-house risk.',datetime('now'),datetime('now'));

-- ── Facet B — Carbon lifecycle ──────────────────────────────────────────
INSERT OR IGNORE INTO participants
  (id, email, password_hash, name, company_name, role, status, kyc_status, bbbee_level, subscription_tier, tenant_id, email_verified, onboarding_completed, phone, job_title, org_website, org_reg_num, bio, created_at, updated_at)
VALUES
 ('persona_b1','thandeka.mabaso@greenfunds.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Thandeka Mabaso','GreenFunds Carbon Fund','carbon_fund','active','approved',1,'enterprise','default',1,1,'+27 83 221 7740','Head of Carbon Origination','https://www.greenfunds.co.za','2016/043910/07','Converts the pipeline from PDD to first issuance profitably and runs ERPA forward cover. 13 years across voluntary and Article 6 markets.',datetime('now'),datetime('now')),
 ('persona_b2','sipho.ndlovu@greenfunds.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Sipho Ndlovu','GreenFunds Carbon Fund','carbon_fund','active','approved',2,'enterprise','default',1,1,'+27 82 447 1908','MRV / Validation Lead (intended: mrv_verifier)','https://www.greenfunds.co.za','2016/043910/07','Stewards every submission through DOE validation to a defensible issuance. Verra VCS and Gold Standard lead auditor; 11 years in MRV.',datetime('now'),datetime('now')),
 ('persona_b3','rajesh.pillay@greenfunds.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Rajesh Pillay','GreenFunds Carbon Fund','carbon_fund','active','approved',2,'professional','default',1,1,'+27 83 618 2253','Carbon Tax Compliance Manager (intended: tax_filer)','https://www.greenfunds.co.za','2016/043910/07','Minimises carbon-tax liability lawfully and files clean SARS returns on time under the Carbon Tax Act. Registered tax practitioner; 10 years in environmental tax.',datetime('now'),datetime('now')),
 ('persona_b4','lerato.mokoena@greenfunds.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Dr Lerato Mokoena','GreenFunds Carbon Fund','carbon_fund','active','approved',1,'enterprise','default',1,1,'+27 84 552 0071','GHG Quantification Engineer (intended: ghg_quant)','https://www.greenfunds.co.za','2016/043910/07','Produces emissions and removals numbers that survive DOE scrutiny and baseline reassessment. PhD in climate science; expert in baseline, project and leakage quantification.',datetime('now'),datetime('now')),
 ('persona_b5','ayanda.khumalo@greenfunds.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Ayanda Khumalo','GreenFunds Carbon Fund','carbon_fund','active','approved',2,'professional','default',1,1,'+27 82 730 4416','Article 6 / ITMO Policy Specialist (intended: a6_policy)','https://www.greenfunds.co.za','2016/043910/07','Keeps every cross-border transfer corresponding-adjusted and double-counting-free under Article 6.2/6.4. LLM in international environmental law.',datetime('now'),datetime('now')),
 ('persona_b6','nadia.davids@greenfunds.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Nadia Davids','GreenFunds Carbon Fund','carbon_fund','active','approved',3,'professional','default',1,1,'+27 83 905 7782','Buffer-Pool / Integrity Risk Analyst (intended: integrity_risk)','https://www.greenfunds.co.za','2016/043910/07','Protects issued-unit integrity across reversals, buffer cancellation and replacement (AFOLU). 9 years in carbon risk and permanence assessment.',datetime('now'),datetime('now'));

-- ── Facet C — IPP project lifecycle ─────────────────────────────────────
INSERT OR IGNORE INTO participants
  (id, email, password_hash, name, company_name, role, status, kyc_status, bbbee_level, subscription_tier, tenant_id, email_verified, onboarding_completed, phone, job_title, org_website, org_reg_num, bio, created_at, updated_at)
VALUES
 ('persona_c1','thandiwe.mokoena@renewcosolar.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Thandiwe Mokoena','RenewCo Solar (Pty) Ltd','ipp_developer','active','approved',1,'enterprise','default',1,1,'+27 83 114 6628','MD, Project Development','https://www.renewcosolar.co.za','2011/072145/07','Owns development-to-financial-close P&L for the project pipeline. Pr.Eng (ECSA), MBA; closed multiple REIPPPP bid windows.',datetime('now'),datetime('now')),
 ('persona_c2','rajen.pillay@renewcosolar.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Rajen Pillay','RenewCo Solar (Pty) Ltd','ipp_developer','active','approved',2,'enterprise','default',1,1,'+27 82 558 3309','Project Finance Lead (intended: ipp_finance)','https://www.renewcosolar.co.za','2011/072145/07','Reaches and maintains financial close — CPs, drawdowns, security and covenant reporting. CFA; 12 years in project finance.',datetime('now'),datetime('now')),
 ('persona_c3','lerato.dlamini@oweng.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Lerato Dlamini','Independent Owners Engineering','ipp_developer','active','approved',2,'professional','default',1,1,'+27 84 661 2204','Owner''s Engineer / Project Controls (intended: owners_engineer)','https://www.oweng.co.za','2015/188204/07','Independent assurance of schedule and cost integrity vs the contract baseline. Pr.Eng (ECSA); CPM/EVM project-controls specialist.',datetime('now'),datetime('now')),
 ('persona_c4','pieter.vandermerwe@buildsaenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Pieter van der Merwe','BuildSA Energy EPC (Pty) Ltd','epc_contractor','active','approved',3,'professional','default',1,1,'+27 82 904 5571','EPC Construction Director','https://www.buildsaenergy.co.za','2013/094872/07','Delivers mechanical completion, commissioning and COD on programme and to quality under FIDIC Silver Book. Pr.Eng (ECSA), CIDB 9CE.',datetime('now'),datetime('now')),
 ('persona_c5','nomvula.khumalo@renewcosolar.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Nomvula Khumalo','RenewCo Solar (Pty) Ltd','ipp_developer','active','approved',1,'enterprise','default',1,1,'+27 83 277 9914','REIPPPP Bid Manager (intended: bid_manager)','https://www.renewcosolar.co.za','2011/072145/07','Wins the bid window with a compliant, competitive REIPPPP/RFP response. 10 years in bid management across BW4–BW7.',datetime('now'),datetime('now')),
 ('persona_c6','sipho.ndlovu@renewcosolar.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Sipho Ndlovu','RenewCo Solar (Pty) Ltd','ipp_developer','active','approved',1,'professional','default',1,1,'+27 82 845 6630','ED / Socio-Economic Development Officer (intended: ed_officer)','https://www.renewcosolar.co.za','2011/072145/07','Meets every REIPPPP ED/SED commitment and survives DMRE/IPPO audit. 9 years in economic-development compliance.',datetime('now'),datetime('now')),
 ('persona_c7','fatima.adams@renewcosolar.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Fatima Adams','RenewCo Solar (Pty) Ltd','ipp_developer','active','approved',2,'professional','default',1,1,'+27 83 660 1187','Environmental & Permitting Specialist (intended: env_specialist)','https://www.renewcosolar.co.za','2011/072145/07','Keeps the project lawful under NEMA/EA, water-use and air-emission licensing. EAPASA-registered EAP; 11 years in environmental compliance.',datetime('now'),datetime('now'));

-- ── Facet D — Grid / System Operator ────────────────────────────────────
INSERT OR IGNORE INTO participants
  (id, email, password_hash, name, company_name, role, status, kyc_status, bbbee_level, subscription_tier, tenant_id, email_verified, onboarding_completed, phone, job_title, org_website, org_reg_num, bio, created_at, updated_at)
VALUES
 ('persona_d1','thandeka.mahlangu@ntcsa.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Thandeka Mahlangu','National Transmission Company SA','grid_operator','active','approved',1,'enterprise','default',1,1,'+27 83 401 7730','System Operations Manager','https://www.ntcsa.co.za','2021/735406/07','Owns grid security and the operational integrity of every SO instruction. Pr.Eng (ECSA); 17 years in grid control and dispatch.',datetime('now'),datetime('now')),
 ('persona_d2','sipho.ndlovu@ntcsa.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Sipho Ndlovu','National Transmission Company SA','grid_operator','active','approved',2,'enterprise','default',1,1,'+27 82 556 8841','Real-Time Dispatch Engineer (intended: grid_dispatcher)','https://www.ntcsa.co.za','2021/735406/07','Keeps the system balanced second-to-second via dispatch and reserve calls. Pr.Eng (ECSA); SCADA/EMS control-room specialist.',datetime('now'),datetime('now')),
 ('persona_d3','rene.vandermerwe@ntcsa.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','René van der Merwe','National Transmission Company SA','grid_operator','active','approved',2,'enterprise','default',1,1,'+27 84 117 6692','Grid Connection & Capacity Manager (intended: grid_connections)','https://www.ntcsa.co.za','2021/735406/07','Runs the connection queue fairly, moving IPPs from application to energised connection under the NTCSA 2024 Capacity Rules. 13 years in network access.',datetime('now'),datetime('now')),
 ('persona_d4','lerato.dlamini@ntcsa.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Lerato Dlamini','National Transmission Company SA','grid_operator','active','approved',1,'professional','default',1,1,'+27 83 774 2218','Transmission Pricing / Wheeling Analyst','https://www.ntcsa.co.za','2021/735406/07','Bills TUoS correctly and defends every wheeling charge through dispute. 10 years in transmission tariff and use-of-system pricing.',datetime('now'),datetime('now')),
 ('persona_d5','johan.pretorius@ntcsa.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Johan Pretorius','National Transmission Company SA','grid_operator','active','approved',3,'professional','default',1,1,'+27 82 330 5519','Grid-Code Compliance Engineer','https://www.ntcsa.co.za','2021/735406/07','Holds every connected facility to the Grid Code / NRS 097, to disconnection. Pr.Eng (ECSA); 12 years in grid-code compliance monitoring.',datetime('now'),datetime('now')),
 ('persona_d6','nomvula.khoza@ntcsa.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Nomvula Khoza','National Transmission Company SA','grid_operator','active','approved',1,'enterprise','default',1,1,'+27 83 902 4471','Ancillary Services / Reserves Trader (intended: reserves_desk)','https://www.ntcsa.co.za','2021/735406/07','Procures the right reserve portfolio at least cost and settles activations fairly. 9 years in ancillary-services procurement.',datetime('now'),datetime('now'));

-- ── Facet E — Lending / Project & Infrastructure Finance ────────────────
INSERT OR IGNORE INTO participants
  (id, email, password_hash, name, company_name, role, status, kyc_status, bbbee_level, subscription_tier, tenant_id, email_verified, onboarding_completed, phone, job_title, org_website, org_reg_num, bio, created_at, updated_at)
VALUES
 ('persona_e1','thandeka.mokoena@infracapitalpartners.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Thandeka Mokoena','Infrastructure Capital Partners','lender','active','approved',1,'enterprise','default',1,1,'+27 83 226 7714','Director, Project & Infrastructure Finance','https://www.infracapitalpartners.co.za','2008/026517/07','Owns the energy book — origination, portfolio appetite and regulator posture. CFA; 20 years arranging senior secured debt for SA IPPs.',datetime('now'),datetime('now')),
 ('persona_e2','sipho.naidoo@infracapitalpartners.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Sipho Naidoo','Infrastructure Capital Partners','lender','active','approved',2,'enterprise','default',1,1,'+27 82 660 1148','Credit Risk Analyst','https://www.infracapitalpartners.co.za','2008/026517/07','Screens and credit-assesses each facility before committee under NCA/Basel III. 8 years in project-finance credit risk.',datetime('now'),datetime('now')),
 ('persona_e3','lerato.dube@infracapitalpartners.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Lerato Dube','Infrastructure Capital Partners','lender','active','approved',2,'professional','default',1,1,'+27 84 551 9930','Portfolio Monitoring / Covenant Officer','https://www.infracapitalpartners.co.za','2008/026517/07','Keeps every live facility compliant — certificates in, breaches caught, cure clocks running. 11 years in portfolio monitoring.',datetime('now'),datetime('now')),
 ('persona_e4','riaan.vanwyk@infracapitalpartners.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Riaan van Wyk','Infrastructure Capital Partners','lender','active','approved',3,'professional','default',1,1,'+27 82 338 6605','Loan Workout / Restructuring Specialist','https://www.infracapitalpartners.co.za','2008/026517/07','Takes distressed facilities from event-of-default to resolution at least loss. 14 years in restructuring and recovery.',datetime('now'),datetime('now')),
 ('persona_e5','naledi.khumalo@infracapitalpartners.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Naledi Khumalo','Infrastructure Capital Partners','lender','active','approved',1,'professional','default',1,1,'+27 83 904 2217','Financial Modeller (DSCR/LLCR)','https://www.infracapitalpartners.co.za','2008/026517/07','Builds and maintains the project cashflow models every covenant rests on. CA(SA); expert in DSCR/LLCR sculpting and P50/P90 sensitivities.',datetime('now'),datetime('now')),
 ('persona_e6','aisha.patel@infracapitalpartners.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Aisha Patel','Infrastructure Capital Partners','lender','active','approved',2,'professional','default',1,1,'+27 82 771 4408','ESG / Equator Principles Officer (intended: esg_lender)','https://www.infracapitalpartners.co.za','2008/026517/07','Holds every financed project to its E&S action plan and Equator/IFC commitments. 10 years in sustainable finance.',datetime('now'),datetime('now')),
 ('persona_e7','johan.pretorius@securitytrustco.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Johan Pretorius','Security Trust Company SA','lender','active','approved',2,'enterprise','default',1,1,'+27 83 559 7782','Agency / Security Trustee Manager (intended: security_agent)','https://www.securitytrustco.co.za','2010/118437/07','Perfects, registers, holds and enforces the security package and administers transfers via Deeds/Movable-Property/STRATE. Admitted attorney; 15 years in security agency.',datetime('now'),datetime('now'));

-- ── Facet F — Regulator (NERSA) ─────────────────────────────────────────
INSERT OR IGNORE INTO participants
  (id, email, password_hash, name, company_name, role, status, kyc_status, bbbee_level, subscription_tier, tenant_id, email_verified, onboarding_completed, phone, job_title, org_website, org_reg_num, bio, created_at, updated_at)
VALUES
 ('persona_f1','thandeka.mabaso@nersa.org.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Thandeka Mabaso','NERSA','regulator','active','approved',1,'enterprise','default',1,1,'+27 83 220 5512','Senior Manager, Electricity Regulation','https://www.nersa.org.za','2005/009127/07','Owns division throughput — every licence, tariff, inspection and enforcement clears or escalates. Admitted attorney; 16 years in electricity regulation.',datetime('now'),datetime('now')),
 ('persona_f2','sipho.ndlovu@nersa.org.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Sipho Ndlovu','NERSA','regulator','active','approved',2,'professional','default',1,1,'+27 82 447 3320','Licensing Officer','https://www.nersa.org.za','2005/009127/07','Drives initial-licence and renewal from receipt to grant/refusal without an SLA breach under ERA 4/2006. 9 years in licensing.',datetime('now'),datetime('now')),
 ('persona_f3','refilwe.setshedi@nersa.org.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Refilwe Setshedi','NERSA','regulator','active','approved',1,'professional','default',1,1,'+27 84 661 7790','Compliance & Enforcement Inspector','https://www.nersa.org.za','2005/009127/07','Converts s.10/s.34 inspection findings into graduated enforcement that survives appeal. 11 years in compliance and enforcement.',datetime('now'),datetime('now')),
 ('persona_f4','anand.pillay@nersa.org.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Dr Anand Pillay','NERSA','regulator','active','approved',2,'enterprise','default',1,1,'+27 82 339 1184','MYPD Tariff Economist (intended: regulator_economist)','https://www.nersa.org.za','2005/009127/07','Determines allowed revenue and the tariff cap each MYPD cycle and runs the RCA true-up. PhD Economics; expert in RAB/WACC revenue-requirement modelling.',datetime('now'),datetime('now')),
 ('persona_f5','nokuthula.dlamini@nersa.org.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Nokuthula Dlamini','NERSA','regulator','active','approved',2,'professional','default',1,1,'+27 83 774 6603','Levy & Revenue Officer','https://www.nersa.org.za','2005/009127/07','Assesses and collects the s.5B levy and runs dunning to settlement or write-off. 10 years in revenue and collections.',datetime('now'),datetime('now')),
 ('persona_f6','mandla.khumalo@nersa.org.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Mandla Khumalo','NERSA','regulator','active','approved',3,'professional','default',1,1,'+27 82 905 2218','Complaints / Dispute Adjudicator','https://www.nersa.org.za','2005/009127/07','Resolves ERA s.30 complaints fairly within an URGENT SLA, with a clean appeal path. Admitted attorney; 12 years in dispute resolution.',datetime('now'),datetime('now')),
 ('persona_f7','yusuf.cassiem@nersa.org.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Yusuf Cassiem','NERSA','regulator','active','approved',1,'professional','default',1,1,'+27 83 503 8841','Market Conduct Analyst','https://www.nersa.org.za','2005/009127/07','Runs surveillance scans, triages alerts and files STORs. 8 years in market-conduct analytics.',datetime('now'),datetime('now'));

-- ── Facet G — Esums O&M · OEM-Support · Offtaker/PPA ────────────────────
INSERT OR IGNORE INTO participants
  (id, email, password_hash, name, company_name, role, status, kyc_status, bbbee_level, subscription_tier, tenant_id, email_verified, onboarding_completed, phone, job_title, org_website, org_reg_num, bio, created_at, updated_at)
VALUES
 ('persona_g1','thandeka.mkhize@sunserv.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Thandeka Mkhize','SunServ O&M (Pty) Ltd','esco','active','approved',1,'enterprise','default',1,1,'+27 83 471 2204','O&M Operations Director','https://www.sunserv.co.za','2017/061204/07','Keeps the fleet at guaranteed availability/PR and holds O&M cost/MWh down. Pr.Eng (ECSA); 14 years in renewable O&M.',datetime('now'),datetime('now')),
 ('persona_g2','riaan.botha@sunserv.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Riaan Botha','SunServ O&M (Pty) Ltd','support','active','approved',2,'professional','default',1,1,'+27 82 660 7715','Reliability & Predictive-Maintenance Engineer (intended: esco)','https://www.sunserv.co.za','2017/061204/07','Converts telemetry into pre-failure intervention that beats the NTT 30% benchmark. Pr.Eng (ECSA); operates the predictive-asset-health brain.',datetime('now'),datetime('now')),
 ('persona_g3','nomvula.dlamini@sunserv.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Nomvula Dlamini','SunServ O&M (Pty) Ltd','esco','active','approved',1,'professional','default',1,1,'+27 84 551 0093','HSE / SHEQ Manager','https://www.sunserv.co.za','2017/061204/07','Zero-harm: every incident investigated, every high-risk task permitted before work under OHSA/NEMA. 12 years in SHEQ.',datetime('now'),datetime('now')),
 ('persona_g4','sipho.nkosi@sunserv.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Sipho Nkosi','SunServ O&M (Pty) Ltd','esco','active','approved',2,'professional','default',1,1,'+27 82 338 4471','Spare-Parts / Supply-Chain Planner','https://www.sunserv.co.za','2017/061204/07','Right part, right site, before the stockout costs generation. 9 years in spares planning; VED-criticality and predictive-RUL demand.',datetime('now'),datetime('now')),
 ('persona_g5','pieter.vanwyk@oemservice.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Pieter van Wyk','OEM Service Partners SA','support','active','approved',3,'professional','default',1,1,'+27 83 904 6628','OEM Warranty & Service Manager','https://www.oemservice.co.za','2015/204880/07','Recovers defective-equipment cost from suppliers, turning claims into cash. 13 years in OEM warranty administration.',datetime('now'),datetime('now')),
 ('persona_g6','anele.mbatha@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Anele Mbatha','Open Energy Platform','support','active','approved',1,'professional','default',1,1,'+27 82 200 7740','ITIL Service & Problem Manager','https://www.openenergy.co.za','2019/004821/07','Restores service fast, kills recurring problems and changes safely under ITIL 4 / ISO 20000-1. ITIL Expert; 10 years in service management.',datetime('now'),datetime('now')),
 ('persona_g7','lerato.modise@cityenergy.gov.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Lerato Modise','City Energy Municipality','offtaker','active','approved',1,'enterprise','default',1,1,'+27 83 776 2218','Group Energy Procurement Lead','https://www.cityenergy.gov.za','2003/011298/07','Secures the cheapest reliable clean MWh and protects the group against PPA downside. 15 years in municipal energy procurement.',datetime('now'),datetime('now')),
 ('persona_g8','yusuf.patel@cityenergy.gov.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Yusuf Patel','City Energy Municipality','offtaker','active','approved',2,'professional','default',1,1,'+27 82 661 5519','PPA Contract Manager','https://www.cityenergy.gov.za','2003/011298/07','Holds both sides to the PPA monthly — volume, price, curtailment and security. 11 years in PPA contract management.',datetime('now'),datetime('now')),
 ('persona_g9','karabo.sithole@cityenergy.gov.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Karabo Sithole','City Energy Municipality','offtaker','active','approved',1,'professional','default',1,1,'+27 84 117 9930','Sustainability & RC Reporting Manager','https://www.cityenergy.gov.za','2003/011298/07','Defensible Scope-2 reduction backed by retired, non-double-counted certificates. 9 years in sustainability and GHG reporting.',datetime('now'),datetime('now'));

-- ── Facet H — Platform / Technical / Cross-cutting ──────────────────────
INSERT OR IGNORE INTO participants
  (id, email, password_hash, name, company_name, role, status, kyc_status, bbbee_level, subscription_tier, tenant_id, email_verified, onboarding_completed, phone, job_title, org_website, org_reg_num, bio, created_at, updated_at)
VALUES
 ('persona_h1','thabo.mokoena@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Thabo Mokoena','Open Energy Platform','admin','active','approved',1,'enterprise','default',1,1,'+27 83 451 2271','Senior Platform / Backend Engineer','https://www.openenergy.co.za','2019/004821/07','Keeps the Hono API coherent as 351 modules and 180+ cascade events accrete. 12 years in backend and distributed-systems engineering.',datetime('now'),datetime('now')),
 ('persona_h2','naledi.khumalo@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Naledi Khumalo','Open Energy Platform','admin','active','approved',2,'enterprise','default',1,1,'+27 82 612 7715','SRE / Edge Reliability Engineer (intended: sre)','https://www.openenergy.co.za','2019/004821/07','Keeps 33 cron triggers, cascade DLQ, advisory locks and latency SLOs green. 10 years in SRE on edge/serverless platforms.',datetime('now'),datetime('now')),
 ('persona_h3','pieter.vandermerwe@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Pieter van der Merwe','Open Energy Platform','admin','active','approved',2,'professional','default',1,1,'+27 84 220 0093','Data Engineer / D1 & Migrations Steward','https://www.openenergy.co.za','2019/004821/07','Owns the 519-migration ledger, the irregular-band discipline and the sharding roadmap. 11 years in data engineering.',datetime('now'),datetime('now')),
 ('persona_h4','aisha.patel@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Aisha Patel','Open Energy Platform','admin','active','approved',1,'enterprise','default',1,1,'+27 83 338 4408','Security Engineer (AppSec / Privacy)','https://www.openenergy.co.za','2019/004821/07','Auth integrity, tenant isolation, POPIA/FICA posture and abuse resistance. CISSP; 12 years in application security.',datetime('now'),datetime('now')),
 ('persona_h5','sipho.dlamini@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Sipho Dlamini','Open Energy Platform','admin','active','approved',2,'professional','default',1,1,'+27 82 730 5519','DevOps / Release Engineer','https://www.openenergy.co.za','2019/004821/07','Ships every push to main safely without burning the prod rate-limiter. 9 years in CI/CD and release engineering.',datetime('now'),datetime('now')),
 ('persona_h6','lerato.nkosi@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Lerato Nkosi','Open Energy Platform','support','active','approved',1,'professional','default',1,1,'+27 83 905 9930','AI / ML Engineer (intended: ml_ops)','https://www.openenergy.co.za','2019/004821/07','Auditable inline AI assists plus the Esums brain that must beat NTT. MSc ML; 8 years in applied ML and MLOps.',datetime('now'),datetime('now')),
 ('persona_h7','yusuf.cassim@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Dr Yusuf Cassim','Open Energy Platform','admin','active','approved',2,'enterprise','default',1,1,'+27 82 916 2218','Platform Product Owner / Solution Architect','https://www.openenergy.co.za','2019/004821/07','Holds the L4/L5 depth rubric and graphify-first discipline as the platform scales. PhD; 15 years in product and solution architecture.',datetime('now'),datetime('now')),
 ('persona_h8','grace.mahlangu@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Grace Mahlangu','Open Energy Platform','support','active','approved',1,'professional','default',1,1,'+27 83 504 7782','QA / Test Automation Engineer','https://www.openenergy.co.za','2019/004821/07','Guards correctness across ~8,369 vitest, 33 Playwright and 3 k6 scenarios. 10 years in test automation.',datetime('now'),datetime('now')),
 ('persona_h9','fatima.adams@openenergy.co.za','pbkdf2$sha256$100000$b3BlbmVuZXJneS1kZW1vLXNhbHQ=$IOJml+OkT8C4tON6R1DA+HDLPXUGnOyqgPF6XBjyYkk=','Fatima Adams','Open Energy Platform','admin','active','approved',2,'professional','default',1,1,'+27 82 200 0093','Tenant / Onboarding Admin','https://www.openenergy.co.za','2019/004821/07','Provisions tenants, drives role onboarding to completion and runs KYC. 9 years in onboarding and identity administration.',datetime('now'),datetime('now'));
