import React from 'react';
import { SuitePage, StatusPill, TabSpec } from '../SuitePage';

export function IppLifecyclePage() {
  const tabs: TabSpec[] = [
    {
      key: 'epc',
      label: 'EPC contracts',
      endpoint: '/ipp/epc',
      description: 'EPC contracts, variations, LDs. Click for contract detail.',
      columns: [
        { key: 'contractor_name', label: 'Contractor' },
        { key: 'lump_sum_zar', label: 'Lump sum', align: 'right', currency: true },
        { key: 'ld_cap_percentage', label: 'LD cap %', align: 'right', number: true },
        { key: 'target_completion_date', label: 'Target', date: true },
        { key: 'commissioning_date', label: 'Commissioning', date: true },
        { key: 'taking_over_certificate_date', label: 'TOC', date: true },
        { key: 'status', label: 'Status', render: (r) => <StatusPill status={String(r.status)} /> },
      ],
      create: {
        title: 'Register EPC contract',
        endpoint: '/ipp/epc',
        fields: [
          { name: 'project_id', label: 'Project ID', type: 'text', required: true },
          { name: 'contractor_name', label: 'Contractor name', type: 'text', required: true },
          { name: 'epc_contractor_participant_id', label: 'Contractor participant ID', type: 'text' },
          { name: 'contract_document_id', label: 'Contract doc ID', type: 'text' },
          { name: 'lump_sum_zar', label: 'Lump sum (ZAR)', type: 'number' },
          { name: 'target_completion_date', label: 'Target completion', type: 'date' },
          { name: 'commissioning_date', label: 'Commissioning date', type: 'date' },
          { name: 'taking_over_certificate_date', label: 'TOC date', type: 'date' },
          { name: 'defects_liability_until', label: 'Defects liability until', type: 'date' },
          { name: 'performance_security_zar', label: 'Performance security (ZAR)', type: 'number' },
          { name: 'ld_cap_percentage', label: 'LD cap %', type: 'number', placeholder: '10-15' },
          { name: 'status', label: 'Initial status', type: 'select', options: [
            { value: 'draft', label: 'Draft' },
            { value: 'executed', label: 'Executed' },
            { value: 'construction', label: 'Construction' },
          ], default: 'draft' },
        ],
      },
      rowActions: [
        { label: '+ Variation', endpoint: '/ipp/epc/{id}/variations',
          form: { title: 'Log EPC variation', endpoint: '', fields: [
            { name: 'variation_number', label: 'Variation #', type: 'text', required: true },
            { name: 'description', label: 'Description', type: 'textarea', required: true },
            { name: 'value_zar', label: 'Value (ZAR, signed)', type: 'number', required: true },
            { name: 'time_impact_days', label: 'Time impact (days)', type: 'number' },
          ] },
        },
        { label: '+ LD', tone: 'danger', endpoint: '/ipp/epc/{id}/lds',
          form: { title: 'Assess liquidated damages', endpoint: '', fields: [
            { name: 'event_type', label: 'Event type', type: 'select', required: true, options: [
              { value: 'delay', label: 'Delay' },
              { value: 'performance', label: 'Performance' },
              { value: 'availability', label: 'Availability' },
              { value: 'guaranteed_output', label: 'Guaranteed output' },
            ] },
            { name: 'event_date', label: 'Event date', type: 'date', required: true },
            { name: 'description', label: 'Description', type: 'textarea' },
            { name: 'calculated_amount_zar', label: 'Calculated amount (ZAR)', type: 'number', required: true },
          ] },
        },
      ],
      detail: {
        endpoint: '/ipp/epc/{id}',
        children: [
          { dataKey: 'variations', label: 'Variations', columns: [
            { key: 'variation_number', label: '#' },
            { key: 'description', label: 'Description' },
            { key: 'value_zar', label: 'Value', align: 'right', currency: true },
            { key: 'time_impact_days', label: 'Days', align: 'right', number: true },
            { key: 'status', label: 'Status' },
          ] },
          { dataKey: 'liquidated_damages', label: 'Liquidated damages', columns: [
            { key: 'event_type', label: 'Event' },
            { key: 'event_date', label: 'Date', date: true },
            { key: 'calculated_amount_zar', label: 'Calculated', align: 'right', currency: true },
            { key: 'capped_amount_zar', label: 'Capped', align: 'right', currency: true },
            { key: 'status', label: 'Status' },
          ] },
        ],
      },
    },
    {
      key: 'environmental',
      label: 'Environmental',
      endpoint: '/ipp/environmental/authorisations/{project_id}',
      description: 'NEMA s.24 authorisations, waste licences, water-use licences, heritage permits.',
      columns: [
        { key: 'authorisation_type', label: 'Type' },
        { key: 'reference_number', label: 'Reference' },
        { key: 'competent_authority', label: 'Authority' },
        { key: 'decision', label: 'Decision', render: (r) => r.decision ? <StatusPill status={String(r.decision)} /> : <span>—</span> },
        { key: 'decision_date', label: 'Decision date', date: true },
        { key: 'expiry_date', label: 'Expires', date: true },
      ],
      create: {
        title: 'Log environmental authorisation',
        endpoint: '/ipp/environmental/authorisations',
        fields: [
          { name: 'project_id', label: 'Project ID', type: 'text', required: true },
          { name: 'authorisation_type', label: 'Type', type: 'select', required: true, options: [
            { value: 'environmental_authorisation_s24', label: 'EA (NEMA s.24)' },
            { value: 'waste_licence', label: 'Waste licence' },
            { value: 'water_use_licence', label: 'Water-use licence' },
            { value: 'air_emission_licence', label: 'Air emission licence' },
            { value: 'heritage_permit', label: 'Heritage permit' },
            { value: 'biodiversity_permit', label: 'Biodiversity permit' },
            { value: 'scoping_report', label: 'Scoping report' },
            { value: 'eir_submitted', label: 'EIR submitted' },
            { value: 'amendment', label: 'Amendment' },
          ] },
          { name: 'reference_number', label: 'Reference', type: 'text' },
          { name: 'competent_authority', label: 'Competent authority', type: 'text' },
          { name: 'applied_date', label: 'Applied', type: 'date' },
          { name: 'decision_date', label: 'Decision date', type: 'date' },
          { name: 'decision', label: 'Decision', type: 'select', options: [
            { value: 'pending', label: 'Pending' },
            { value: 'granted', label: 'Granted' },
            { value: 'granted_with_conditions', label: 'Granted with conditions' },
            { value: 'refused', label: 'Refused' },
            { value: 'appealed', label: 'Appealed' },
            { value: 'withdrawn', label: 'Withdrawn' },
          ] },
          { name: 'conditions_text', label: 'Conditions', type: 'textarea' },
          { name: 'expiry_date', label: 'Expiry', type: 'date' },
          { name: 'document_r2_key', label: 'Document R2 key', type: 'text' },
        ],
      },
      rowActions: [
        { label: '+ Condition', endpoint: '/ipp/environmental/authorisations/{id}/conditions',
          form: { title: 'Track EA condition', endpoint: '', fields: [
            { name: 'condition_reference', label: 'Condition reference', type: 'text', required: true },
            { name: 'condition_text', label: 'Text', type: 'textarea', required: true },
            { name: 'due_date', label: 'Due date', type: 'date' },
            { name: 'compliance_status', label: 'Initial status', type: 'select', options: [
              { value: 'pending', label: 'Pending' },
              { value: 'in_progress', label: 'In progress' },
              { value: 'compliant', label: 'Compliant' },
              { value: 'non_compliant', label: 'Non-compliant' },
              { value: 'waived', label: 'Waived' },
            ], default: 'pending' },
            { name: 'evidence_r2_key', label: 'Evidence R2 key', type: 'text' },
          ] },
        },
      ],
    },
    {
      key: 'land',
      label: 'Land parcels',
      endpoint: '/ipp/land/parcels/{project_id}',
      description: 'Owned / leased / servitude / option / communal / state land.',
      columns: [
        { key: 'parcel_number', label: 'Parcel' },
        { key: 'ownership_type', label: 'Ownership' },
        { key: 'area_hectares', label: 'Ha', align: 'right', number: true },
        { key: 'registered_owner', label: 'Registered owner' },
        { key: 'title_deed_number', label: 'Title deed' },
        { key: 'monthly_rent_zar', label: 'Rent/m', align: 'right', currency: true },
        { key: 'status', label: 'Status', render: (r) => <StatusPill status={String(r.status)} /> },
      ],
      create: {
        title: 'Register land parcel',
        endpoint: '/ipp/land/parcels',
        fields: [
          { name: 'project_id', label: 'Project ID', type: 'text', required: true },
          { name: 'parcel_number', label: 'Parcel number', type: 'text' },
          { name: 'sg_diagram', label: 'SG diagram', type: 'text' },
          { name: 'lpi', label: 'LPI', type: 'text' },
          { name: 'ownership_type', label: 'Ownership type', type: 'select', options: [
            { value: 'owned', label: 'Owned' },
            { value: 'leased', label: 'Leased' },
            { value: 'servitude', label: 'Servitude' },
            { value: 'option', label: 'Option' },
            { value: 'communal', label: 'Communal' },
            { value: 'state_land', label: 'State land' },
          ] },
          { name: 'area_hectares', label: 'Area (ha)', type: 'number' },
          { name: 'registered_owner', label: 'Registered owner', type: 'text' },
          { name: 'title_deed_number', label: 'Title deed #', type: 'text' },
          { name: 'deed_registration_date', label: 'Deed registration', type: 'date' },
          { name: 'lease_start_date', label: 'Lease start', type: 'date' },
          { name: 'lease_end_date', label: 'Lease end', type: 'date' },
          { name: 'monthly_rent_zar', label: 'Monthly rent (ZAR)', type: 'number' },
          { name: 'splumap_rezoning_status', label: 'SPLUMA rezoning status', type: 'select', options: [
            { value: 'none', label: 'None' },
            { value: 'applied', label: 'Applied' },
            { value: 'approved', label: 'Approved' },
            { value: 'refused', label: 'Refused' },
          ] },
          { name: 'status', label: 'Status', type: 'select', options: [
            { value: 'identified', label: 'Identified' },
            { value: 'negotiating', label: 'Negotiating' },
            { value: 'secured', label: 'Secured' },
            { value: 'in_dispute', label: 'In dispute' },
            { value: 'released', label: 'Released' },
          ], default: 'secured' },
        ],
      },
    },
    {
      key: 'servitudes',
      label: 'Servitudes',
      endpoint: '/ipp/land/servitudes',   // no GET all for servitudes — admin/operator posts them
      description: 'Powerline, access road, water pipeline, fibre servitudes. Register after Deeds Office registration.',
      columns: [
        { key: 'servitude_type', label: 'Type' },
        { key: 'parcel_number', label: 'Parcel' },
        { key: 'grantor', label: 'Grantor' },
        { key: 'consideration_zar', label: 'Consideration', align: 'right', currency: true },
        { key: 'registered_at_deeds', label: 'Deeds', render: (r) => <span>{r.registered_at_deeds ? 'Yes' : 'No'}</span> },
        { key: 'registration_date', label: 'Registered', date: true },
      ],
      create: {
        title: 'Register servitude',
        endpoint: '/ipp/land/servitudes',
        fields: [
          { name: 'project_id', label: 'Project ID', type: 'text', required: true },
          { name: 'servitude_type', label: 'Type', type: 'select', required: true, options: [
            { value: 'powerline', label: 'Powerline' },
            { value: 'access_road', label: 'Access road' },
            { value: 'water_pipeline', label: 'Water pipeline' },
            { value: 'fibre', label: 'Fibre' },
            { value: 'other', label: 'Other' },
          ] },
          { name: 'parcel_number', label: 'Parcel number', type: 'text' },
          { name: 'grantor', label: 'Grantor', type: 'text' },
          { name: 'consideration_zar', label: 'Consideration (ZAR)', type: 'number' },
          { name: 'registered_at_deeds', label: 'Registered at Deeds?', type: 'checkbox' },
          { name: 'registration_date', label: 'Registration date', type: 'date' },
          { name: 'notes', label: 'Notes', type: 'textarea' },
        ],
      },
    },
    {
      key: 'insurance',
      label: 'Insurance',
      endpoint: '/ipp/insurance/expiring',
      params: { within_days: '180' },
      description: 'Policies expiring in the next 180 days — renew before expiry to stay covenant-compliant.',
      columns: [
        { key: 'policy_number', label: '#' },
        { key: 'policy_type', label: 'Type' },
        { key: 'insurer', label: 'Insurer' },
        { key: 'broker', label: 'Broker' },
        { key: 'sum_insured_zar', label: 'Sum insured', align: 'right', currency: true },
        { key: 'premium_zar', label: 'Premium', align: 'right', currency: true },
        { key: 'period_end', label: 'Expires', date: true },
        { key: 'lenders_noted', label: 'Lender noted', render: (r) => <span>{r.lenders_noted ? 'Yes' : 'No'}</span> },
      ],
      create: {
        title: 'Add insurance policy',
        endpoint: '/ipp/insurance/policies',
        fields: [
          { name: 'project_id', label: 'Project ID', type: 'text', required: true },
          { name: 'policy_number', label: 'Policy #', type: 'text', required: true },
          { name: 'policy_type', label: 'Type', type: 'select', required: true, options: [
            { value: 'car', label: 'CAR (construction all risks)' },
            { value: 'operational_all_risks', label: 'Operational all risks' },
            { value: 'business_interruption', label: 'Business interruption' },
            { value: 'public_liability', label: 'Public liability' },
            { value: 'directors_and_officers', label: 'D&O' },
            { value: 'environmental_liability', label: 'Environmental liability' },
            { value: 'marine_cargo', label: 'Marine cargo' },
            { value: 'delay_in_start_up', label: 'Delay in start-up' },
            { value: 'other', label: 'Other' },
          ] },
          { name: 'insurer', label: 'Insurer', type: 'text', required: true },
          { name: 'broker', label: 'Broker', type: 'text' },
          { name: 'period_start', label: 'Period start', type: 'date', required: true },
          { name: 'period_end', label: 'Period end', type: 'date', required: true },
          { name: 'sum_insured_zar', label: 'Sum insured', type: 'number' },
          { name: 'premium_zar', label: 'Premium', type: 'number' },
          { name: 'deductible_zar', label: 'Deductible', type: 'number' },
          { name: 'lenders_noted', label: 'Lenders noted?', type: 'checkbox' },
          { name: 'document_r2_key', label: 'Document R2 key', type: 'text' },
        ],
      },
      rowActions: [
        { label: 'Claim', tone: 'danger', endpoint: '/ipp/insurance/policies/{id}/claim',
          form: { title: 'Log insurance claim', endpoint: '', fields: [
            { name: 'claim_number', label: 'Claim number', type: 'text', required: true },
            { name: 'loss_event_date', label: 'Loss event date', type: 'date' },
            { name: 'notified_at', label: 'Notified at', type: 'datetime' },
            { name: 'quantum_zar', label: 'Quantum (ZAR)', type: 'number' },
            { name: 'description', label: 'Description', type: 'textarea' },
          ] },
        },
      ],
    },
    {
      key: 'community',
      label: 'Community',
      endpoint: '/ipp/community/ed-sed/{project_id}/summary',
      description:
        'ED/SED spend summary per REIPPPP category. Log individual engagements and spend via the New buttons.',
      columns: [
        { key: 'category', label: 'Category' },
        { key: 'n', label: 'Entries', align: 'right', number: true },
        { key: 'total_zar', label: 'Spend', align: 'right', currency: true },
      ],
      create: {
        title: 'Record ED/SED spend',
        endpoint: '/ipp/community/ed-sed',
        fields: [
          { name: 'project_id', label: 'Project ID', type: 'text', required: true },
          { name: 'category', label: 'Category', type: 'select', required: true, options: [
            { value: 'ownership', label: 'Ownership' },
            { value: 'management_control', label: 'Management control' },
            { value: 'skills_development', label: 'Skills development' },
            { value: 'enterprise_development', label: 'Enterprise development' },
            { value: 'supplier_development', label: 'Supplier development' },
            { value: 'socio_economic_development', label: 'Socio-economic development' },
            { value: 'preferential_procurement', label: 'Preferential procurement' },
            { value: 'localisation', label: 'Localisation' },
            { value: 'jobs_created', label: 'Jobs created' },
          ] },
          { name: 'period', label: 'Period', type: 'text', required: true, placeholder: 'Q2-2026' },
          { name: 'amount_zar', label: 'Amount (ZAR)', type: 'number', required: true },
          { name: 'beneficiary', label: 'Beneficiary', type: 'text' },
          { name: 'description', label: 'Description', type: 'textarea' },
          { name: 'reipppp_bid_window', label: 'REIPPPP bid window', type: 'text' },
          { name: 'evidence_r2_key', label: 'Evidence R2 key', type: 'text' },
        ],
      },
    },
  ];
  return (
    <SuitePage
      title="IPP project file"
      subtitle="EPC, environmental, land, insurance and community — the full project-finance evidence pack."
      tabs={tabs}
    />
  );
}
