-- Retrospective backfill: Goldrush Operations (p_live_goldrush, offtaker) is the
-- counterparty buying power from GoNXT's 10 real private-wire C&I solar sites.
-- Derived entirely from the real ipp_projects fleet (capacity/location/COD), NOT invented.
-- Energy is a CALCULATED retrospective: annual MWh = capacity_mw * 8760h * 0.20 CF
-- (conservative SA C&I rooftop fixed-tilt) = capacity_mw * 1752. SA grid factor 0.94 tCO2e/MWh.
-- Idempotent: INSERT OR IGNORE with deterministic ids derived from project id.

-- Site group: the consolidated C&I brand portfolio.
INSERT OR IGNORE INTO offtaker_site_groups
  (id, participant_id, group_name, group_type, billing_entity, consolidated_invoice, cost_centre)
VALUES
  ('sg_goldrush_ci', 'p_live_goldrush', 'Goldrush C&I Portfolio', 'brand',
   'Goldrush Operations (Pty) Ltd', 1, 'GR-ENERGY');

-- Delivery point per private-wire site (LV behind-the-meter, ~0.4 kV).
INSERT OR IGNORE INTO offtaker_delivery_points
  (id, participant_id, name, location, meter_id, voltage_kv, nmd_kva, annual_kwh, tariff_category, status)
SELECT
  'dp_' || substr(id, 6), 'p_live_goldrush', project_name, location,
  'MTR-' || substr(id, 6, 8), 0.4, round(capacity_mw * 1000),
  round(capacity_mw * 1752 * 1000), 'commercial_lv', 'active'
FROM ipp_projects WHERE developer_id = 'p_live_gonxt';

-- REC certificates: completed generation years 2024 (Mar-Dec) + 2025 (full),
-- generated by GoNXT, held by Goldrush. Status issued = active for the homepage tile.
INSERT OR IGNORE INTO rec_certificates
  (id, certificate_serial, generator_participant_id, project_id,
   generation_period_start, generation_period_end, mwh_represented, technology,
   registry, issuance_date, status, owner_participant_id)
SELECT
  'rec_' || substr(id, 6) || '_2024', 'SAREC-' || substr(id, 6, 10) || '-2024',
  'p_live_gonxt', id, '2024-03-01', '2024-12-31',
  round(capacity_mw * 1752 * 10.0 / 12.0, 2), 'solar', 'SAREC', '2025-01-15', 'issued', 'p_live_goldrush'
FROM ipp_projects WHERE developer_id = 'p_live_gonxt'
UNION ALL
SELECT
  'rec_' || substr(id, 6) || '_2025', 'SAREC-' || substr(id, 6, 10) || '-2025',
  'p_live_gonxt', id, '2025-01-01', '2025-12-31',
  round(capacity_mw * 1752, 2), 'solar', 'SAREC', '2026-01-15', 'issued', 'p_live_goldrush'
FROM ipp_projects WHERE developer_id = 'p_live_gonxt';

-- Published Scope 2 disclosures (location + market based), grid factor 0.94 tCO2e/MWh,
-- renewable covering ~55% of total C&I consumption.
INSERT OR IGNORE INTO scope2_disclosures
  (id, participant_id, reporting_year, total_consumption_mwh, location_based_emissions_tco2e,
   market_based_emissions_tco2e, renewable_mwh_claimed, renewable_percentage,
   grid_factor_tco2e_per_mwh, audit_reference, status, published_at, created_by)
VALUES
  ('s2_goldrush_2024', 'p_live_goldrush', 2024, 2548.4, 2395.5, 1077.6, 1401.6, 55.0, 0.94,
   'GR-S2-2024', 'published', '2025-03-31', 'p_live_goldrush'),
  ('s2_goldrush_2025', 'p_live_goldrush', 2025, 3058.0, 2874.5, 1293.7, 1681.9, 55.0, 0.94,
   'GR-S2-2025', 'published', '2026-03-31', 'p_live_goldrush');

-- Land Goldrush on /horizon.
UPDATE participants SET onboarding_completed = 1, onboarding_step = 'completed', updated_at = datetime('now')
WHERE id = 'p_live_goldrush';
