/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        /* ═══ SAP Fiori 3 Quartz Light Palette ═══ */
        'fiori-shell': '#354a5f',
        'fiori-shell-hover': '#283848',
        'fiori-brand': '#0a6ed1',
        'fiori-brand-hover': '#085caf',
        'fiori-brand-light': '#427cac',
        'fiori-action': '#0854a0',
        'fiori-canvas': '#f5f6f7',
        'fiori-surface': '#ffffff',
        'fiori-surface-alt': '#fafafa',
        'fiori-header': '#edeff0',
        'fiori-border': '#d9d9d9',
        'fiori-border-strong': '#89919a',
        'fiori-border-soft': '#e5e5e5',
        'fiori-text': '#32363a',
        'fiori-text-sub': '#515559',
        'fiori-text-mute': '#6a6d70',
        'fiori-text-faint': '#89919a',
        'fiori-success': '#107e3e',
        'fiori-success-bg': '#ebf5eb',
        'fiori-warning': '#e9730c',
        'fiori-warning-bg': '#fef7e6',
        'fiori-error': '#bb0000',
        'fiori-error-bg': '#ffebeb',
        'fiori-info': '#0a6ed1',
        'fiori-info-bg': '#e5f0fa',
        'fiori-neutral': '#6a6d70',
        'fiori-neutral-bg': '#eff1f2',
        'fiori-accent-indigo': '#5d36ff',
        'fiori-accent-teal': '#0d7b84',
        'fiori-accent-pink': '#ab218e',
        'fiori-accent-plum': '#6e1f6f',

        /* ═══ IonEx tokens mapped to Fiori (for existing component compat) ═══ */
        'ionex-brand': '#0a6ed1',
        'ionex-brand-light': '#427cac',
        'ionex-brand-deep': '#0854a0',
        'ionex-accent': '#0a6ed1',
        'ionex-accent-deep': '#085caf',
        'ionex-mint': '#107e3e',

        'ionex-shell': '#354a5f',
        'ionex-shell-bg': '#354a5f',
        'ionex-shell-fg': '#ffffff',
        'ionex-canvas': '#f5f6f7',
        'ionex-surface': '#ffffff',
        'ionex-surface-alt': '#fafafa',
        'ionex-border': '#d9d9d9',
        'ionex-border-soft': '#e5e5e5',
        'ionex-text': '#32363a',
        'ionex-text-sub': '#515559',
        'ionex-text-mute': '#89919a',

        'ionex-success': '#107e3e',
        'ionex-success-bg': '#ebf5eb',
        'ionex-warning': '#e9730c',
        'ionex-warning-bg': '#fef7e6',
        'ionex-error': '#bb0000',
        'ionex-error-bg': '#ffebeb',

        /* Legacy Open Energy (fallback) */
        oe: {
          forest: '#1a3d2e',
          'forest-dark': '#0f261d',
          'forest-light': '#2d5a44',
          accent: '#c9a227',
          'accent-dark': '#a68620',
          cream: '#f5f1e8',
          'cream-dark': '#e8e2d3',
          gold: '#d4af37',
          sage: '#8fbc8f',
          slate: '#2c3e50',
        },
      },
      fontFamily: {
        sans: ['"72"', '"72full"', '"72 Full"', 'Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Arial', 'sans-serif'],
        display: ['"72"', '"72full"', 'Inter', 'Georgia', 'serif'],
        mono: ['"72 Mono"', 'JetBrains Mono', 'Consolas', 'monospace'],
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
        'space-16': '64px',
        'shell-height': '44px',
        'sidebar': '256px',
        'sidebar-collapsed': '48px',
        'tile-std': '176px',
        'tile-compact': '88px',
      },
      borderRadius: {
        'radius-xs': '2px',
        'radius-sm': '4px',
        'radius-md': '6px',
        'radius-lg': '8px',
        'radius-pill': '9999px',
      },
      boxShadow: {
        'shadow-sm': '0 0 1px 0 rgba(0,0,0,0.2), 0 1px 2px 0 rgba(0,0,0,0.08)',
        'shadow-md': '0 0 1px 0 rgba(0,0,0,0.2), 0 2px 8px 0 rgba(0,0,0,0.10)',
        'shadow-lg': '0 0 2px 0 rgba(0,0,0,0.2), 0 8px 24px 0 rgba(0,0,0,0.12)',
        'shadow-focus': '0 0 0 2px rgba(10,110,209,0.4)',
        'fiori-tile': '0 0 1px 0 rgba(0,0,0,0.25), 0 1px 2px 0 rgba(0,0,0,0.05)',
        'fiori-tile-hover': '0 0 1px 0 rgba(0,0,0,0.4), 0 4px 12px 0 rgba(0,0,0,0.12)',
      },
      maxWidth: {
        'max-content': '1440px',
      },
      transitionTimingFunction: {
        'ease-ionex': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'ease-fiori': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      width: {
        'sidebar': '256px',
        'sidebar-collapsed': '48px',
        'tile-std': '176px',
        'tile-compact': '88px',
      },
      height: {
        'shell': '44px',
        'tile-std': '176px',
      },
    },
  },
  plugins: [],
};
